.github/ISSUE_TEMPLATE.md

Let's make life easier for the community =)
See https://help.github.com/en/articles/about-issue-and-pull-request-templates

Add an Issue template

---

src/linter/root.go

properly annotate remaining phpdoc report call

---

src/cmd/main.go

So we can use defer inside main function safely.
Updates #45

cmd: use single point of exit in main

---

src/cmd/main.go
src/linter/report.go

cmd: print all supported checks with their summary in -help output

---

src/linter/report.go

linter: fix typo in check documentation

---

src/cmd/main.go

They work in the same way as they do in the standard
Go toolchain. Both are useful for profiling.
Updates #45

cmd: add -memprofile and -cpuprofile flags

---

src/linter/block.go
src/linttest/basic_test.go

linter: fix unused false positive for prop fetch

---

src/linter/block.go
src/linttest/basic_test.go
src/solver/exprtype.go

resolve float types to "float", not "double"

---

src/linttest/exprtype_test.go

linttest: add tests for expression type resolving

---

example/custom/custom_test.go

Use linttest package for testing.

example: update tests

---

src/linttest/exprtype_test.go

linttest: add keyed array lit types test

---

src/solver/exprtype.go

Accidentally left an import of fmt that isn't needed.

Remove unused import

---

src/cmd/main.go

If we write those to outputFp, we destroy JSON output.
Instead of doing jsonOutput branching and using different
output descriptors for it, just write that warning to
stderr in all cases.

Write "you can't disable linter for file" to stderr

---

src/linter/root.go
src/meta/metainfo.go
src/state/update.go

Also records current method info.

carry CurrentFunction info inside ClassParseState as well

---

src/langsrv/completion.go
src/langsrv/defs.go
src/langsrv/dummywalker.go
src/langsrv/hover.go
src/langsrv/langsrv.go
src/langsrv/refs.go
src/langsrv/refsvisitors.go
src/langsrv/state.go

fix langsrv

---

src/linter/block.go
src/linter/report.go
src/linttest/basic_test.go
src/meta/typesmap.go

add bitwiseOps checker

---

src/linttest/basic_test.go

That check was not covered by tests.

add tests for "complexity" check

---

src/linter/block.go
src/linttest/basic_test.go
src/linttest/oop_test.go

run andWalker for stmt.ElseIf

---

src/linter/cache.go

If there are no custom checks, cache file looks like this:
[ver][data]
Where data is gob-encoded.
Previous format for combined cache looked like this:
[ver][data][x-ver-len1][x-ver1][x-data1]...[x-ver-lenN][x-verN][x-dataN]
Where each data is expected to be gob-encoded (but it's not a restriction).
This resulted in data corruptions due to the mix of write-byte and gob-encode
operations through shared reader/writer.
Potentially better format packs all versions in the header:
[ver][x-ver-len1][x-ver1]...[x-ver-lenN][x-verN][data][x-data1]...[x-dataN]
|                                             /
header---------------------------------------/
It also makes version check faster, we don't need to call custom Decode
on the outdated cache file data.
Signed-off-by: Iskander Sharipov …

change combined cache file layout

---

src/linter/block.go
src/linttest/basic_test.go

compact('a', 'b') is equivalent to ['a' => $a, 'b' => $b]. This change looks up
variables corresponding to its arguments and treats them as variable references.

Handle implicit variable references in compact()

---

src/langsrv/langsrv.go
src/linter/custom.go
src/linter/root.go
src/linttest/basic_test.go

Fix all mentioned misspellings in the code.
Resolves #186

#186 Fix reported misspells in the code base

---

src/langsrv/refs.go
src/linter/cache.go
src/linter/report.go

Fix unconvert linting issues to address #187

Fix unconvert linting issues

---

src/cmd/flags.go
src/langsrv/langsrv.go

Fix misspell linting issues

---

.travis.yml
Makefile

enable Travis and run basic checks during the build

---

README.md

Resolves Issue #201 "readme: add travis CI badge"
Placed badge next to heading

Added Travis CI build status badge

---

src/cmd/main.go

Hi @quasilyte
I made the changes that you requested on issue #203  
What I did:
- Added single version info print at every command except `-version`

add ability to set version on bash and show version

---

src/linttest/oop_test.go

Resolves Issue #206 
Renamed test from fix to issue #1

rename TestInterfaceConstants to TestIssue1

---

src/linttest/trait_test.go

Renamed test from fix to issue #183

rename TestTraitInstanceProperties to TestIssue183

---

src/linttest/oop_test.go

Renamed test from fix to issue #2

rename TestReturnTypes to TestIssue2

---

src/linttest/oop_test.go

Renamed test from fix to issue #3

rename TestVariadic to TestIssue3

---

src/linttest/trait_test.go

Renamed test from fix to issue #6

rename TestTraitProperties to TestIssue6

---

src/linttest/oop_test.go

Renamed test from fix to issue #8

rename TestMagicMethods to TestIssue8

---

src/linttest/oop_test.go

Renamed test from fix to issue #11

rename TestGenerator to TestIssue11

---

src/linttest/oop_test.go

Renamed test from fix to issue #16

rename TestInterfaceInheritance to TestIssue16

---

src/linttest/basic_test.go

Renamed test from fix to issue #37

rename TestUnusedInPropFetch to TestIssue37

---

src/linttest/basic_test.go

Renamed test from fix to issue #128

rename TestIssetShortCircuit to TestIssue128

---

Makefile
README.md
build-example.sh
main.go
src/cmd/main.go

Make it easier for users to get a binary that include build info.
Also modify version printing a little bit.

add "make install"

---

src/linttest/basic_test.go

Renamed tests from fix to issue #26

rename TestIssetVar to TestIssue26

---

src/linttest/trait_test.go

Renamed test from fix to issue #182

rename TestTraitSelf to TestIssue182

---

src/linttest/deadcode_test.go

Renamed tests from fix to issue #78

Rename TestDeadCodeDie to TestIssue78_1, TestDeadCodeNoReturn to TestIssue78_2, TestTrailingExit to TestIssue78_3

---

src/linttest/basic_test.go

Fix https://github.com/VKCOM/noverify/issues/86

fixed opened php tag in test

---

src/linter/root.go
src/linttest/basic_test.go

Fix https://github.com/VKCOM/noverify/issues/86

Check for void type in func params

---

src/linter/block.go
src/linter/cache.go

apply #237 suggestions

---

src/meta/typesmap.go

meta: make TypesMap.Find order deterministic

---

src/linter/custom.go

linter: fix bug coming from 13bdab0471ca4888ef320c32f2a5979ce5e823b1

---

src/linter/block.go
src/linttest/basic_test.go
src/linttest/exprtype_test.go

linter: fix class static prop fetch handling for $$

---

README.md

You can preview it at https://github.com/sergey-shambir/noverify/tree/concise-readme

docs: made README more concise

---

src/linter/utils.go
src/linttest/rules_test.go

https://wiki.php.net/rfc/object-typehint

add "object" type support for rules

---

example/custom/main.go
src/linter/root.go
src/solver/exprtype.go

all: make type asserts on *node.Argument unckecked

---

src/phpgrep/matcher_test.go

${"*"}-related benchmarks.
Adding them before starting doing any optimizations on it.

phpgrep: add more benchmarks

---

src/phpgrep/matcher_test.go

Remove source parsing time from the benchmarks
by executing matcher over already parsed AST.

phpgrep: fix benchmarks

---

src/linttest/basic_test.go
src/linttest/linttest.go

linttest: add "@linter disable" test

---

src/linttest/basic_test.go

linttest: add bareTry check test

---

src/cmd/main.go
src/linter/block.go
src/linter/root.go
src/linttest/oop_test.go
src/meta/metainfo.go
src/php/parser/scanner/lexer.go
src/phpgrep/matcher_test.go

Commits:
```
linter: simplify parsePHPDocVar method
linttest: remove BadModifiers test
phpgrep: fix input param accidental shadowing
meta: remove commented-out debug print stmt
all: fix style issues found by linters
```

Various small fixes

---

docs/install.md

docs: fix git clone URL

---

src/linttest/exprtype_test.go

linttest: add a test for malformed phpdoc var names

---

src/linter/cache.go
src/linttest/basic_test.go
src/linttest/typesmap_test.go
src/meta/typesmap.go
src/solver/exprtype.go

fixed plus (+) operator type inference for arrays

---

src/cmd/main.go
src/linter/conf.go
src/linttest/golden_test.go
src/linttest/linttest.go
src/linttest/testdata/ctype/LICENSE.txt
src/linttest/testdata/ctype/ctype.php
src/linttest/testdata/idn/LICENSE.txt
src/linttest/testdata/idn/golden.txt
src/linttest/testdata/idn/idn.php
src/linttest/testdata/parsedown/LICENSE.txt
src/linttest/testdata/parsedown/golden.txt
src/linttest/testdata/parsedown/parsedown.php
src/linttest/testdata/qrcode/LICENSE.txt
src/linttest/testdata/qrcode/golden.txt
src/linttest/testdata/qrcode/qrcode.php
src/linttest/testdata/underscore/LICENSE.txt
src/linttest/testdata/underscore/golden.txt
src/linttest/testdata/underscore/underscore.php

The testdata suite can be extended later.
Also added LoadStubs option to linttest test suite.
It's a dependencies slice that can be used to load
only the required parts of stubs => its fast.
Can be used for #250 later.

linttest: add golden file based tests

---

src/linttest/rules_test.go
src/rules/util.go

Also fix rules->string function.

linttest: add implode() rule test

---

src/linttest/golden_test.go
src/linttest/testdata/phprocksyd/LICENSE.txt
src/linttest/testdata/phprocksyd/Phprocksyd.php
src/linttest/testdata/phprocksyd/Simple.php
src/linttest/testdata/phprocksyd/golden.txt

linttest: add phprocksyd to a golden test suite

---

src/linter/block.go
src/linter/report.go
src/linttest/basic_test.go

Similar to Go "evaluated but not used" compilation error.

add discardExpr check

---

src/linter/report.go

linter: register voidResultUsed check

---

src/linttest/linttest.go

linttest: fix reports printing

---

Gopkg.lock
Gopkg.toml

Signed-off-by: Iskander (Alex) Sharipov <quasilyte@gmail.com>

remove unused deps

---

src/cmd/flags.go
src/cmd/git_main.go

Add flag to disable exclusion of changes on master

---

src/linter/parser.go

We used filepath.Walk before, now we use godirwalk.Walk.
filepath.Walk does not follow symlinks, but it does
accept it as a root argument without an error.
godirwalk.Walk can traverse symlinks with FollowSymbolicLinks=true,
but we don't use it. It will give an error if root is
a symlink, so we avoid calling Walk() on them.
This fix attempts to restore the old behavior.
Also added logging of the actual traversal error to
make this error debugging easier in the future.

src/linter: don't do Fatal if filename is a symlink

---

src/linter/block.go
src/linter/block_context.go
src/linttest/function_exists_test.go

linter: add function_exists support

---

src/linter/block.go
src/linttest/regression_test.go
src/linttest/testdata/parsedown/golden.txt

linter: treat $a[...] as $a usage

---

src/linter/block.go
src/linter/utils.go
src/linttest/regression_test.go

linter: handle more isset forms

---

src/linter/block.go
src/linttest/basic_test.go
src/meta/typesmap.go
src/solver/exprtype.go

Document that IsArray and IsArrayOf are not a proper
choice for solved types.

remove typesmap IsInt and IsString + add some docs

---

src/linter/block.go
src/linter/root.go
src/linter/utils.go

linter: remove duplicated normalizeType method

---

src/linter/block.go
src/linter/phpdoc_util.go
src/linter/root.go
src/linter/utils.go
src/linttest/exprtype_test.go
src/linttest/phpdoc_test.go

WIP: linter: normalize ("fix") phpdoc types for class @var

---

src/meta/typestring.go

meta: fix WBaseMethodParam comment format

---

src/linttest/bench_test.go
src/linttest/linttest.go

linttest: add solver benchmarks

---

src/linttest/exprtype_test.go
src/solver/exprtype.go

solver: preserve type of the clone expr

---

src/linttest/golden_test.go
src/linttest/testdata/options-resolver/Debug/OptionsResolverIntrospector.php
src/linttest/testdata/options-resolver/Exception/AccessException.php
src/linttest/testdata/options-resolver/Exception/ExceptionInterface.php
src/linttest/testdata/options-resolver/Exception/InvalidArgumentException.php
src/linttest/testdata/options-resolver/Exception/InvalidOptionsException.php
src/linttest/testdata/options-resolver/Exception/MissingOptionsException.php
src/linttest/testdata/options-resolver/Exception/NoConfigurationException.php
src/linttest/testdata/options-resolver/Exception/NoSuchOptionException.php
src/linttest/testdata/options-resolver/Exception/OptionDefinitionException.php
src/linttest/testdata/options-resolver/Exception/UndefinedOptionsException.php
src/linttest/testdata/options-resolver/LICENSE
src/linttest/testdata/options-resolver/OptionConfigurator.php
src/linttest/testdata/options-resolver/Options.php
src/linttest/testdata/options-resolver/OptionsResolver.php
src/linttest/testdata/options-resolver/README.md
src/linttest/testdata/options-resolver/function.php
src/linttest/testdata/options-resolver/golden.txt
src/linttest/testdata/options-resolver/php8.php

linttest: add options-resolver to the golden test suite

---

src/linttest/golden_test.go
src/linttest/testdata/twitter-api-php/LICENSE.md
src/linttest/testdata/twitter-api-php/TwitterAPIExchange.php
src/linttest/testdata/twitter-api-php/golden.txt
src/linttest/testdata/twitter-api-php/index.php

linttest: add twitter-api-php to the golden test suite

---

src/linter/cache_test.go

linter: add global vars to a cache test

---

src/linttest/rules_test.go

linttest: rule tests: add "var" matcher class test

---

src/linttest/exprtype_test.go
src/solver/exprtype.go

solver: handle bitwise ops

---

src/linttest/exprtype_test.go

linttest: add expr type tests for NoReplace vars

---

src/linter/root.go

When a root walker encounters declare(strict_types=1),
it sets strictTypes field to true, so type-related
checks can use it to adjust the behavior.

linter: recognize declare(strict_types=1) in root walker

---

src/linttest/exprtype_test.go

linttest: add more tests for type precision

---

src/linter/block.go

linter: simplified node comparison

---

src/phpdoc/type_parser.go
src/phpdoc/type_parser_test.go

phpdoc: skip whitespace only inside ()<>{} groups

---

src/linter/block.go
src/linttest/shape_test.go

linter: report phpdocType warnings for local @var

---

src/langsrv/langsrv.go

Fixed SymbolKind for documentSymbol handler
off topic: Can I create and publish a VSCode extension to use this Language Server?

langsrv: Fixed SymbolKind for documentSymbol handler

---

src/linter/utils.go
src/solver/oop.go

Like GetClassName, it expands a name node to a FQN, if possible.
This function is useful in custom linters that need to
resolve function names.

solver: add GetFuncName

---

src/linter/types.go
src/linttest/shape_test.go

linter: permit FQN forms of shape and tuple type

---

src/linter/root.go
src/linttest/oop_test.go
src/phpdoc/parser.go
src/phpdoc/parser_test.go

linter,phpdoc: parse property-read and property-write

---

src/linttest/golden_test.go
src/linttest/testdata/options-resolver/golden.txt

cmd/stubs: update stubs to add php8-related things

---

docs/dynamic-rules.md

New features being:
* Function grouping
* Namespaces

docs/dynamic-rules: add new features description

---

src/linttest/golden_test.go
src/linttest/testdata/math/LICENSE
src/linttest/testdata/math/README.md
src/linttest/testdata/math/golden.txt
src/linttest/testdata/math/src/BigDecimal.php
src/linttest/testdata/math/src/BigInteger.php
src/linttest/testdata/math/src/BigNumber.php
src/linttest/testdata/math/src/BigRational.php
src/linttest/testdata/math/src/Exception/DivisionByZeroException.php
src/linttest/testdata/math/src/Exception/IntegerOverflowException.php
src/linttest/testdata/math/src/Exception/MathException.php
src/linttest/testdata/math/src/Exception/NegativeNumberException.php
src/linttest/testdata/math/src/Exception/NumberFormatException.php
src/linttest/testdata/math/src/Exception/RoundingNecessaryException.php
src/linttest/testdata/math/src/Internal/Calculator.php
src/linttest/testdata/math/src/Internal/Calculator/BcMathCalculator.php
src/linttest/testdata/math/src/Internal/Calculator/GmpCalculator.php
src/linttest/testdata/math/src/Internal/Calculator/NativeCalculator.php
src/linttest/testdata/math/src/RoundingMode.php

linttest: add brick/math to the test suite

---

main.go
src/baseline/baseline.go
src/baseline/baseline_test.go
src/cmd/conf.go
src/cmd/main.go

baseline: store LinterVersion inside a profile

---

src/baseline/baseline.go
src/baseline/baseline_test.go
src/cmd/linter_runner.go

cmd: add missing file.Close() + return Stats from baseline.ReadProfile

---

src/linter/report.go
src/linttest/golden_test.go

Solve: Windows golden tests failed #572

---

src/linttest/oop_test.go
src/linttest/rules_test.go

Move TestInterfaceRules to oop_test.go. Solve #577

---

src/linttest/exprtype_test.go
src/solver/exprtype.go

Solve: handle prefix/infix ++ and -- in exprtype #462

---

src/linter/block.go
src/linttest/rules_test.go

Since Cond is a part of `n` node, when we do n.Walk,
we also walk the condition. In elseif case we need to
handle condition with walkCond and then walk the rest
with n.Stmt.Walk, so the double walk for the cond
doesn't happen.

linter: traverse elseif cond only once

---

src/linttest/golden_test.go
src/linttest/testdata/baseline-test/baseline.json
src/linttest/testdata/baseline-test/golden.txt
src/linttest/testdata/baseline-test/src/file1.php
src/linttest/testdata/baseline-test/src/file2.php

linttest: add baseline e2e tests

---

.gitignore
src/cmd/main.go
src/linter/root.go
src/linttest/golden_test.go

linter: fixed bug when GoldenTest failed on Windows

---

src/linter/custom.go

linter: add ReportByLint to external linters API

---

src/linter/root.go

Also fix checkerName typo in Report() calls
(should be magicMethodDecl instead of magicMethod).

linter: refactor magicMethodDecl implementation

---

src/cmd/flags.go
src/cmd/git_main.go
src/git/diff.go
src/langsrv/langsrv.go
src/langsrv/refsvisitors.go
src/langsrv/state.go
src/linter/block.go
src/linter/conf.go
src/linter/report.go
src/linter/root.go
src/meta/typesmap.go
src/php/parser/node/expr/assign/n_coalesce.go
src/php/parser/node/expr/n_arrow_function.go
src/php/parser/php7/parser.go
src/php/parser/position/position.go
src/php/parser/scanner/token.go
src/solver/solver.go
src/tests/checkers/misspell_test.go
src/tests/checkers/typesmap_test.go

This is a preparation step before we enable linters on CI.

Fixed issues found by Go linters

---

.golangci.yml
Makefile
src/linter/block.go
src/php/parser/php7/php7_test.go

Some files from php/parser were added to ignore list as a temporary solution.
Commit contains unused constant which should trigger the build failure if everything is configured correctly.

Makefile: run golangci-lint on "check"

---

src/ir/irfmt/printer_test.go

ir/irfmt: port AST printer tests to IR printer

---

src/cmd/git_main.go

We passed nil allow disable regexp for git mode.

cmd: fix -allow-disable for git mode

---

src/cmd/flags.go
src/cmd/php-guru/dupcode/fileindexer.go
src/cmd/php-guru/dupcode/main.go
src/cmd/php-guru/dupcode/utils.go
src/ir/normalize/normalize.go
src/ir/normalize/normalize_test.go

cmd/php-guru: run indexing and use meta info in ir/normalization

---

src/ir/irfmt/printer_test.go

ir/irfmt: add <?php to test cases implicitly

---

src/constfold/eval.go
src/linter/block_linter.go
src/linter/cache.go
src/linter/cache_test.go
src/meta/const_value.go
src/meta/constantvaluetype_string.go
src/tests/checkers/basic_test.go

meta,linter,constfold: handle Bool-typed const values

---

src/constfold/eval.go
src/linter/cache.go
src/linter/cache_test.go
src/linter/root.go
src/tests/checkers/basic_test.go

linter: save const value of define()-ed consts

---

src/cmd/php-guru/dupcode/main.go

cmd/php-guru: skip files with parse errors

---

src/linttest/linttest.go

linttest: mark SimpleNegativeTest as test helper

---

src/linter/worker.go

The benefits are the same, but we don't pay for the
synchronization and it's always good to throw away
another global variable.

linter: use scratchBuf instead of the sync.Pool

---

src/ir/get_node_kind.go
src/tests/golden/testdata/embeddedrules/lib.php

ir: add AnonClassExpr node kind

---

src/ir/ir.go
src/ir/node_types.go

ir: types.go -> node_types.go + move ifaces to ir.go

---

src/linter/block.go

linter: refactor handleAssignOp

---

src/lintdoc/lintdoc.go
src/lintdoc/lintdoc_test.go

lintdoc: render Quickfix flag in the output

---

src/ir/irfmt/printer.go
src/ir/irfmt/printer_test.go

See https://github.com/z7zmey/php-parser/pull/116

ir/irfmt: fix array item expr printing with unpack=true

---

src/ir/irfmt/printer_test.go

ir/irfmt: simplify printer tests for single line cases

---

src/ir/ir.go
src/ir/node_types.go

ir: document most ir nodes

---

src/linter/root.go

This logic is borrowed from the ruleguard.
An example when it's useful:
```php
$x = $x + 1; // Suggest ++$x
$x = $x + $y; // Suggest $x += $y
```
If we define both rules without a short-circuiting, we'll get 2 warnings per `$x = $x + 1` pattern as the second rule will match it as well.

linter: add short circuit logic for rules matching

---

src/phpgrep/compile.go
src/tests/rules/rules_error_test.go

phpgrep: added check for unknown matcher class

---

src/linter/block.go
src/tests/regression/issue778_test.go

linter: don't report callStatic warnings for traits

---

src/linttest/linttest.go
src/tests/checkers/indexing_order_test.go
src/tests/checkers/shape_test.go
src/tests/rules/rules_test.go

Because there is an `AddNamedFile` method

linttest: removed unnecessary AddNamedFile function

---

src/linter/block.go
src/solver/exprtype.go
src/tests/exprtype/exprtype_test.go

solver: added type inference for the null coalesce operator

---

src/linter/cache.go
src/linter/cache_test.go
src/linter/phpdoc_util.go
src/linter/root.go
src/meta/metainfo.go
src/solver/solver.go
src/tests/checkers/oop_test.go

linter: added support for @mixin annotation

---

src/linter/cache_test.go

linter: add traits to cache tests

---

.github/workflows/go.yml
README.md

Travis is removed and should be disabled.

try using the GitHub actions

---

src/linter/block.go
src/linter/report.go
src/linter/superglobals.go
src/tests/checkers/basic_test.go

linter: added discardVar check

---

src/phpgrep/matcher.go
src/phpgrep/matcher_test.go

Do we miss any other cases? ...

phpgrep: fix panic on ir.CatchStmt matching

---

src/ir/irconv/irconv.go
src/ir/irutil/clone.go
src/ir/node_types.go
src/state/update.go

ir: make GroupUseStmt.Prefix field type more precise

---

src/ir/irconv/irconv.go
src/ir/irutil/clone.go
src/ir/node_types.go
src/state/update.go

```go
ir.GroupUseStmt.UseType -> *ir.Identifier
ir.UseStmt.Use          -> *ir.Name
ir.UseListStmt.UseType  -> *ir.Identifier
```
#866

ir: clarified types for some nodes

---

src/cmd/git_main.go
src/cmd/linter_runner.go
src/linter/conf.go
src/workspace/git_files.go

This reverts commit 9b0fd5c5d67ebb17a2032fb0fbf80fdf7851a37c.

Revert "cmd: associate absolute paths with git files (#873)"

---

src/ir/irutil/nodepath.go
src/linter/block.go
src/linter/custom.go

linter: move NodePath to irutil

---

example/custom/custom_test.go
example/custom/main.go
src/cmd/check.go
src/cmd/conf.go
src/cmd/flags.go
src/cmd/git_main.go
src/cmd/help.go
src/cmd/linter_runner.go
src/cmd/main.go
src/lintdoc/lintdoc.go
src/lintdoc/lintdoc_test.go
src/linter/cache.go
src/linter/cache_test.go
src/linter/conf.go
src/linter/custom.go
src/linter/linter.go
src/linter/report.go
src/linter/root.go
src/linter/worker.go
src/linttest/golden_linttest.go
src/linttest/linttest.go
src/tests/checkers/basic_test.go
src/tests/checkers/kphp_test.go
src/tests/checkers/misspell_test.go
src/tests/custom/path_test.go
src/tests/exprtype/exprtype_test.go
src/tests/golden/golden_test.go
src/tests/golden/quickfix_test.go
src/tests/rules/rules_test.go

Checkers are now bound to the config instead of a global state.

all: make checkers registry non-global

---

src/ir/node_types.go
src/linter/block_linter.go
src/linter/report.go
src/tests/checkers/emptystmt_test.go
src/tests/checkers/oop_test.go

Report redundant empty empty statements (nop statements).

linter: add emptyStmt checker

---

example/custom/custom_test.go
src/linttest/golden_linttest.go
src/linttest/linttest.go
src/tests/checkers/basic_test.go
src/tests/checkers/kphp_test.go
src/tests/checkers/misspell_test.go
src/tests/custom/path_test.go
src/tests/golden/quickfix_test.go
src/tests/rules/rules_test.go

linttest: improve linttest config and linter related code

---

src/linttest/linttest.go
src/tests/rules/multipattern_test.go
src/tests/rules/rules_test.go

We may need to test the rules outside of NoVerify, this change will allow us to do that.

linttest: testing using rules is part of the linttest API

---

src/linter/block_linter.go
src/linter/report.go
src/linter/root.go
src/tests/checkers/basic_test.go
src/tests/checkers/oop_test.go

linter: renamed nameCase to nameMismatch

---

src/linter/worker.go

Moved the repeated code to the new `parseWithCache()` method.

linter: remove code duplication in `Worker.IndexFile()` method

---

src/cmd/embeddedrules/rules.php
src/tests/golden/testdata/embeddedrules/callSimplify.php
src/tests/golden/testdata/embeddedrules/golden.txt
src/tests/golden/testdata/embeddedrules/ternarySimplify.php
src/tests/golden/testdata/flysystem/golden.txt
src/tests/golden/testdata/mustache/golden.txt
src/tests/golden/testdata/parsedown/golden.txt
src/tests/golden/testdata/qrcode/golden.txt
src/tests/golden/testdata/quickfix/ternarySimplify.php
src/tests/golden/testdata/quickfix/ternarySimplify.php.fix.expected
src/tests/golden/testdata/twitter-api-php/golden.txt
src/tests/golden/testdata/underscore/golden.txt

Simplify
```php
$x[$i] !== null ? $x[$i] : $y;
// to
$x[$i] ?? $y;
array_key_exists($i, $x) ? $x[$i] : $y;
// to
$x[$i] ?? $y;
substr($x, $y, 1);
// to
$x[$y];
array_push($a, $v);
// to
$a[] = $v;
```
#332

linter: added some checks from phpinspectionsea

---

src/cmd/embeddedrules/rules.php
src/tests/inline/testdata/embeddedrules/returnAssign.php

Report the use of an assignment in a return statement.
#332

cmd/embeddedrules: add returnAssign checker

---

src/linter/block_linter.go
src/linter/report.go
src/linter/root.go
src/tests/checkers/var_shadow_test.go
src/tests/golden/testdata/underscore/golden.txt

`varShadow` checks that the variables from the
key and the variable in foreach did not shadow
the parameters of the current function.

linter: added varShadow checker

---

src/cmd/git_main.go
src/cmd/main.go

cmd: fixed suggest of fix flag when the flag is already provided

---

src/linter/worker.go
src/php/parseutil/parseutil.go

linter: fixed panic if file cannot be parsed

---

src/linter/block_linter.go
src/solver/solver.go
src/tests/checkers/basic_test.go
src/utils/utils.go

linter: added check for class name case in const fetch

---

src/cmd/cli.go

Before:
```
flag provided but not defined: -some-flag
Usage of check:
-allow-all-checks
Enable all checks, including those disabled by default
-allow-checks string
Comma-separated list of check names to be enabled (default "<all>")
...
-stubs-dir string
Directory with phpstorm-stubs
-unused-var-regex string
Regexp that specifies variable name that will not be given...
2021/07/08 15:44:11 flag provided but not defined: -some-flag
```
After
```
2021/07/08 15:44:43 Flag --some-flag not found for 'check' command
Usage:
$ noverify check [options] [args] - The command to lint files
Arguments:
folders/files     Folders and/or files for check
Options:
Checks:
--allow-checks (default: <all>)
Comma-separated list of check names to be enabled
--allow-all-checks (default: false)
Enable all checks, …
```

cmd: fixed output if the flag is not found

---

src/linter/report.go
src/linter/root.go
src/meta/metainfo.go
src/tests/inline/testdata/checkers/invalidExtendClass.php

It checks the inheritance of the class from the final class.

linter: added `invalidExtendClass` checker

---

README.md
docs/install.md

- Added telegram chat ro readme
- Fixed install doc

docs: minor fixes

---

src/linter/block.go
src/linter/root.go
src/linter/root_checker.go

linter: moved function check in `rootChecker`

---

src/cmd/linter_runner.go

Add stdout report output

---

src/phpdoc/parser.go

Adds `@inheritDoc` case to search in phpdoc comment

inheritDoc comment

---

src/linter/conf.go
src/linter/root.go
src/tests/infra/pathRulesSet_config_test.go

tied with [prototype](https://github.com/VKCOM/noverify/pull/1236).

linter: base system for on path rule filtering
