VKCOM/noverify

- README.md
Makes "examples" text element clickable.
> readme: use a link element when referring examples

- src/git/catter.go
- src/git/diff.go
- src/linter/root.go
- src/solver/exprtype.go
This commit rewrites some if-else-if-else chains as a switch.
Based on Go style guide:
https://golang.org/doc/effective_go.html#switch
Found by https://go-critic.github.io/overview#ifElseChain-ref
> Rewrite if-else-if-else to switch statements

- src/linter/basic_test.go
- src/linter/block.go
Suggest using short [] form instead.
> linter: report usages of array() literals

- README.md
- example/custom/custom_test.go
- example/custom/main.go
- src/cmd/main.go
- src/linter/block.go
- src/linter/custom.go
- src/linter/parser.go
- src/linter/root.go
This is probably a transitional step into a better support
of named checks. For now, caller of the Report can optionally
prepend check name that can be later extracted using CheckName() method.
As a demonstration of how this can be used, -exclude-checks flag
is implemented.
Even if internal representation of check names and/or Report()
API would change, -exclude-checks behavior will stay the same.
I'm planning to use CheckName() method inside linter tests to filter-out
all unrelated warnings.
Updates #27
> annotate most reports, add -exclude-checks CLI param

- example/custom/custom_test.go
- example/custom/main.go
- src/langsrv/refsvisitors.go
- src/linter/block.go
- src/linter/custom.go
- src/linter/parser.go
- src/linter/root.go
Turn root/block contexts into structs for now.
- Simpler to add more state to the public API bridge.
- Easier to find implementation (jump to relevant impl from the code)
Added XxxDefaults types for embedding to provide a simple
way to add stub interface implementations.
> linter: add AfterLeaveFile method to RootChecker interface

- src/linter/basic_test.go
- src/linter/block.go
Found this case when tried to check phpmyadmin codebase.
> fix varToString panic on ${"x"} and ${"{$x}"}

- src/linter/custom.go
Makes it possible to get current filename from the custom checks.
> linter: add Filename method to the RootContext

- src/linter/basic_test.go
- src/linter/block.go
- src/linter/root.go
- src/meta/metainfo.go
- src/meta/scope.go
Add support for variable-variable tracking inside a scope
as well, so we don't mark usages of $$x inside if body
as undefined. isset($$x) defines $x along $$x, so usages
of $x are permitted inside that body as well.
Doesn't work for arbitrary indirection level,
isset($$$x) is not supported (but it won't panic, as it did before).
Updates #26
> linter,meta: fix panic during isset($$x)

- src/linter/basic_test.go
- src/linter/block.go
Supported markers:
"fallthrough",
"fall through",
"falls through",
"no break",
Marker is expected to be a first comment line substring.
Both // and /* comment styles are handled.
Fixes #24
> linter: add caseBreak check support fallthrough comment

- src/linter/basic_test.go
- src/linter/block.go
If we are about to emit undefined const warning,
check if that const is actually one of [null,false,true].
In that case, report invalid const name case instead
of saying that referenced constant is undefined.
> linter: better warning for undefined null/false/true

- README.md
- example/custom/main.go
- src/cmd/main.go
- src/linter/block.go
- src/linter/custom.go
- src/linter/report.go
- src/linter/root.go
Makes possible to run some checks in a separation,
which is useful in CI and while testing a new check.
Also makes it possible to have "disabled by default" checks
that are useful, but not for every linter user. It's also
easier to leave some checks disabled by default if they have
some correctness issues that can't be solved in a short period of time.
To figure out what checks are enabled by default we introduce
structured diagnostics info, linter.CheckInfo.
It's not mandatory to register a check with linter.DeclareCheck,
but it's the only way to associate metadata with diagnostics
implemented by any checker.
Non-declared checks can't be enabled by default, so
explicit -allow-checks entry should be specified for them.
> cmd: add -allow-checks argument

- src/linter/block.go
- src/linter/report.go
- src/linttest/basic_test.go
Finds expressions of form `(T)v` where `v` already
known to have a type of `T`. In those cases, type cast
can be removed.
Severity is minimal.
Not enabled by default.
Use -allow-checks redundantCast to run it.
Feature-request by @atercattus
> linter: add redundantCast check

- src/git/diff.go
Previously, break on EOF was associated to the
enclosing switch, so it resulted to the infinite loop.
Make loop labeled and break using that label to avoid that.
> git: fix EOF handling in git.Diff

- src/linter/block.go
- src/linter/root.go
- src/linttest/phpdoc_test.go
For functions with `@param` comment line like:
@param $foo - best foo ever
We would register "-" as a type of $foo,
which breaks other diagnostics that rely on the type inference.
> linter: don't register \- as a param type

- src/linter/root.go
- src/linttest/basic_test.go
- src/linttest/oop_test.go
Also some minor fixes to public class phpdoc checker:
- Don't require comment for interface methods
- Permit methods with leading "_" to lack phpdoc comment (e.g. __call)
> linttest: use filters when testing specific check

- src/linter/block.go
- src/linter/report.go
Split arrayKeys into:
- mixedArrayKeys
- dupArrayKeys
> linter: make arrayKeys check 2 different checks

- src/linter/block.go
- src/linter/report.go
- src/linttest/basic_test.go
Detects "continue" (without level) usage inside switch
that behaves identically to "break".
As a consequence, it's either a bad style (if it's used
instead of break on purpose) or a bug (if "continue"
was intended, if there is a "for" loop outside).
Since both cases are bad, we report any continue (w/o level)
usage inside switch cases.
> linter: add caseContinue check

- src/linter/block.go
This fixes a warning from statitccheck (S1011).
> linter: use append with ... instead of loop+append

- src/linter/block.go
- src/linttest/basic_test.go
It stopped to find unused vars inside switch statements due
to the recent change with innermostLoop check.
Returned insideLoop flag. We could collect the "loop path"
and lookup whether we have any loopFor there, but flag
seems simpler and solves the problem for now.
> linter: fix unused check regression

- src/linter/root.go
- src/linttest/phpdoc_test.go
Using type alias inside type hint (php7) have unexpected
results. To avoid confusion during php5->php7 transition,
require users to use real primitive type names instead of their aliases.
> linter: handle all type aliases inside phpdoc check

- src/linter/block.go
- src/linttest/basic_test.go
It's not correct to report code after "or die" as unreachable.
If it's desired to discourage die usages, it should be done
in a different way. "Unreachable code" error here is confusing.
> linter: don't tread "or die" as unconditional exit

- src/linter/custom.go
Sometimes block-scoped checks need to know the filename as well.
Removed "full name" promise from the documentation as it may not
be the case if linter input was not created inside "cmd", which
does map paths to abs paths. In tests we don't do this, so
Filename() does not return the full name inside them.
> linter: add Filename() to the BlockContext

- src/linter/block.go
- src/linttest/deadcode_test.go
This makes deadCode properly handle "returns sometimes" case
for nested statements that create a nested block context.
Fixes #78
> propagate exit flags from foreach/for/while/etc

- example/custom/main.go
- src/cmd/conf.go
- src/cmd/main.go
The callback is called after flag.Parse is called
inside cmd.Main function. This makes it easier
to use flags that are defined outside of cmd.Main.
Used config struct instead of global variables
to make the configuration possibility obvious for the users.
This breaks backwards-compatibility though.
> cmd: add MainConfig with AfterFlagParse hook

- main.go
- src/inputs/inputs.go
- src/langsrv/refs.go
- src/langsrv/state.go
- src/linter/cache.go
- src/linter/conf.go
- src/linter/parser.go
- src/linttest/linttest.go
Add inputs package that defines SourceInput interface.
That interface is used inside linter to read PHP files.
Readers returned from that interface should yield UTF-8 encoded
data. If other encodings are needed, it's possible to handle
them inside linter extensions by providing custom implementation
and assigning it to linter.SrcInput.
Example that adds win-1251 encoding support will be added soon
to show how it can be done.
This is experimental part of the linter and can be a subject of
changes in future. Only UTF-8 support is guaranteed.
> all: use inputs.SourceInput for PHP reading

- src/cmd/main.go
- src/linter/block.go
- src/linter/conf.go
- src/linter/report.go
- src/linttest/basic_test.go
Makes it possible to set "_" as a valid prefix for unused variables.
Useful for tuple-like returns that are destructured using list.
Only one value is used:
```
list($_id, $_name, $email) = getUser(...);
```
If $_ is used everywhere, it's less opparent what fields are ignored:
```
list($_, $_, $email) = getUser(...);
```
The next step is to warn on usages of variables that are matched
by IsDiscardVar. If such variable is read, it could be a mistake.
By default, only "$_" is permitted, as before.
For arbitrary patterns regexp is used.
> accept unused-var-regex option

- src/linter/block.go
- src/linter/report.go
- src/linttest/basic_test.go
Fixes dupArrayKeys false positive where 2 keys, ' and "
were considered as equal due to the quote trimming
(both were trimmed to the empty string).
> Use unquote that removes at most one '/"

- src/linter/block.go
- src/linter/root.go
- src/linttest/exprtype_test.go
- src/linttest/oop_test.go
- src/solver/exprtype.go
- src/solver/oop.go
- src/solver/solver.go
This change enables more precise handling of `$this` and `static`
types that are quite common in Fluent APIs.
The idea is to carry the current class type along the type resolving
and map "static" pseudo-type into concrete class type.
Fixes #89
> Handle late static binding

- src/linttest/exprtype_test.go
- src/linttest/oop_test.go
- src/solver/solver.go
Now that NoVerify understands `static` type,
given appropriate annotations, it can handle SimpleXMLElement
without any hacks.
An example of such (proper) types annotation:
https://github.com/VKCOM/phpstorm-stubs/commit/faff1841c257873c35abfacf09cf8fac2fb3bdaa
> Add tests for SimpleXMLElement/Iterator support

- src/linter/cache.go
- src/linter/root.go
- src/linttest/exprtype_test.go
- src/linttest/oop_test.go
- src/meta/encoding_test.go
- src/meta/typesmap.go
- src/solver/solver.go
If no other type info about params is available,
walk base types to find matching method and see whether
it has proper types info for that parameter.
Do this only for interfaces.
This makes it possible to resolve both input and output
types of methods that implement some interface. In turn,
this makes "undefined method" go away if method had no
PHPDoc that specified the parameter type that was used.
Phpstorm and phpdoc utility do more or less the same thing.
> inherit base method param types

- src/cmd/main.go
It's defined but not used.
Remove for now to avoid misliading info in -help output.
If it's needed, it can be returned back and
be actually implemented.
> cmd: remove unused -git-local flag

- src/linter/root.go
- src/linttest/exprtype_test.go
- src/linttest/phpdoc_test.go
When `@param` annotation misses variable type,
we should ignore it instead of using the variable name as a type.
Before this fix, NoVerify inferred \$a to be a type for $a
parameter out of `@param $a` line.
This fix is required to avoid false positives from arrayAccess.
> improve handling of invalid phpdoc annotations

- src/linttest/basic_test.go
There are reports that this caused warnings in past.
Can't reproduce them now, but tests are still usefull
to avoid unexpected regression.
> add a test for assignments in for loops

- src/linter/root.go
- src/linttest/oop_test.go
This is required to fix argCount warning about
"not enough" arguments when 0 args are passed for
variadic parameter.
Added a test case that covers that.
> treat ...$ variadic param as optional

- src/linter/report.go
Makes staticcheck more happy about ./src/linter package.
> remove unused fmtReports func

- src/linter/block.go
- src/linttest/basic_test.go
If we don't do it, we can miss some important code
fragements, like variable usages.
This change modifies getCaseStmts method so it
returns <case cond, body statements> instead of
<isDefault, body statements>. It's still trivial
to check case cond for nil to determine "default"
case, but it's also easy to walk case expression
at the same time.
Fixes #109
> walk switch "case" clauses during analysis

- src/cmd/main.go
Allocate new slice for results instead.
> cmd: remove inplace reports filtering

- src/linter/block.go
- src/linttest/basic_test.go
When instanceof is inside if condition, it introduces
a new tracked var via b.addVar().
It seems to be incorrect for cases where added variable
was already used above.
Given that we enter (walk) instanceof LHS before
we add that new variable, instanceof itself doesn't
end up marking that variable as used.
This change makes linter stop tracking instanceof LHS.
(We add it to the scope directly instead.)
> fix false positives with instanceof

- src/linter/block.go
- src/linttest/basic_test.go
!empty is sometimes used in place of isset when
variable is about to be checked for both not being
null and is defined as well as checking that it's
"not empty" in one go.
This change makes non-empty expressisons
handled in a same way as isset expressions inside
if statement condition.
> handle !empty($x) inside conditions like isset($x)

- src/linter/block.go
If block context RootState is called before RootContext.State(),
then we're returning nil map that can cause nil map assignment panic.
If block checkers used to collect info and propagate it to the
root context that can handle "before leave file", we should
call State() method that does map allocation in case it's nil.
> fix BlockContext.RootState panic

- src/linter/parser.go
- src/linttest/basic_test.go
When doing root level code analysis using BlockWalker,
predefine argc and argv variables, so they don't cause
"undefined variable" warnings inside global scope.
This doesn't break the requirement to do `global $argc`
or `global $argv` when using them from non-global scope.
> predefine argc and argv vars for the global scope

- src/linter/block.go
- src/linter/cache.go
- src/linter/report.go
- src/linter/root.go
- src/linttest/phpdoc_test.go
- src/meta/metainfo.go
This change adds basic support for detecting usages of
deprecated functions and methods.
We might extend it to also warn about different
deprecated symbols (like classes), but initial feature
request only asked about functions.
For this code:
mysql('a', 'b', 'c');
Gives a warning:
Call to deprecated function mysql (5.3.0 Use mysql_db_query instead.)
Updates #15
> add "deprecated" check for functions and methods

- src/linter/block.go
- src/linttest/basic_test.go
Move isset/!empty/instanceof handling inside andWalker,
so we check all expressions and define vars sequentially,
following the && operator short-circuit behavior.
Helps to avoid false positives in:
if (isset($x) && use($x)) {...}
Fixes #128
> improve handling of if conditions

- src/linter/block.go
- src/linter/block_context.go
- src/linter/parser.go
- src/linter/root.go
Since custom block walkers can't reliably propagate their state
to the nested custom block checkers (that are created by constructor
function), they loose needed state when entering these blocks.
Since PHP is function-scoped and all other blocks do not create
real scopes, it's intuitive that function block walker lives for
the entire function body. This is especially important if that
checker collects function-bound info, like global'ed variables.
Moved all non-shared (between contexts) data into a separate struct
that became a part of BlockWalker. All other fields are considered
to be safe to share between nested contexts.
> Don't copy block walker and custom walkers for nested blocks

- .gitignore
- README.md
- src/cmd/flags.go
- src/cmd/main.go
Use github.com/go-bindata/go-bindata to pack github.com/VKCOM/phpstorm-stubs
into src/cmd/stubs and use it from the compiled binary from default.
To re-generate stubs, the following steps should be used:
1. Clone github.com/VKCOM/phpstorm-stubs into src/cmd/stubs
2. Run "go generate"
(Comments inside code tell the same.)
The phpstorm-stubs folder (git repo) is ignored,
generated file (phpstorm_stubs.go) is commited.
If user provides explicit -stubs-dir override, use that instead.
> use embedded stubs by default

- src/linter/root.go
- src/linttest/oop_test.go
It was using old convention where tag was a part of the
message separated by `:`.
Unfortunately, both tag and message have string type,
therefore code continued to compile, but tag was invalid
and the check never worked since it's registered by a different tag.
> Fix "modifiers" check tag.

- src/cmd/flags.go
- src/cmd/main.go
-critical expects a comma-separated list of check names
that will cause "critical reports" count go up and make
NoVerify perform non-zero exit status in the end.
If no -critical is specified (or empty string is given),
old behavior is used, all reports except of MAYBE level
are considered critical.
Fixes #140
Fixes #66
Updates #58
> add -critical command line argument

- src/linter/block.go
- src/linter/report.go
- src/linter/root.go
phpdoc only checks for phpdoc existence.
phpdocLint checks phpdoc comment correctness.
> split phpdoc into phpdoc and phpdocLint

- README.md
- src/cmd/flags.go
- src/cmd/git_main.go
- src/cmd/main.go
Makes it possible to have generated files to living outside of
git repository for indexing purposes.
If no explicit target arguments are provided, linter behaves
as before.
> use flag.Args() as index-only targets in git/diff mode

- src/cmd/flags.go
- src/cmd/git_main.go
- src/git/ls.go
With -git-include-untracked (default=true) unstaged files are
indexed and analyzed.
The switch is only applied to gitRepoComputeReportsFromLocalChanges,
because untracked files can only exist if work tree have any changes.
> Add -git-include-untracked switch to diff mode

- src/linter/block.go
- src/linttest/basic_test.go
Issue caused by updated php-parser library.
Was not detected by any of our tests.
Fixes #150
> fix foreach by ref var handling

- src/linter/block.go
- src/linttest/basic_test.go
If the last argument in a function call is a splat, e.g., `foo(...$x)`, then assume it is an array with enough elements to match the function's signature.
> Fix handling of splat arguments

- src/linter/block.go
- src/linttest/basic_test.go
This fixes false positives saying that `$x` is unused when it is used as a property (or static property) name, e.g., `->$x` or `::$$x`.
> Recognize variable uses in property name subexpressions

- src/linter/report.go
- src/linter/root.go
If php code contains invalid modifier, it would be a syntax error
and code would not be properly parsed.
It means that we can't test/reproduce "modifiers" checker warnings.
Handle unknown modifiers as an internal sanity check inside linter
and give "linterError" instead of an ordinary warning.
> linter: remove "modifiers" check

- src/langsrv/state.go
- src/linter/cache.go
- src/linter/custom.go
- src/linter/parser.go
If a custom root checker records some info during the
indexing phase that is required during the analysis, it
must be written to cache, because otherwise that
checker is not going to be executed if cache exists while
that cache would still not contain relevant data.
Make it possible to register a checker along with
associated MetaCacher that can write needed parts
to the cache files and load that info during
cache file reading.
MetaCacher also includes a Version() method
that can be used to implement cache invalidation.
> add custom meta cacher support

- src/linter/block.go
- src/linttest/basic_test.go
The list of more strictly checked functions might extend over time.
If it gets big, we probably may want to discuss how to express
this kind of constraints in phpstorm meta files (stubs),
so that info can be reused in both phpstorm and noverify.
Fixes #163
> linter: handle mt_rand in argCount check

- src/linter/block.go
- src/linter/report.go
- src/linter/root.go
- src/linter/utils.go
- Move Report type to report.go
- Move utility functions from block.go and root.go to utils.go,
since their usage (and scope) is not limited to either
(and some of them are even exported).
> linter: move Report type and util funcs

- src/linter/root.go
- phpdoc checks for phpdoc presence,
- phpdocLint checks for phpdoc errors and other issues
> linter: rename missed phpdoc check to phpdocLint

- src/linter/block.go
- src/linttest/basic_test.go
Avoids false positives in "undefined" check when list
is used as foreach value.
Fixes #172
> add foreach list value support

- src/linter/block.go
- src/linter/cache.go
- src/linter/report.go
- src/linter/root.go
- src/linttest/basic_test.go
- src/linttest/oop_test.go
- src/meta/metainfo.go
Detect when static methods are called using "->" syntax
and instance methods that are called using "::" syntax.
It's not always a mistake, but could be a sign of a code smell.
Also, it makes code harder to read, since it's not apparent
what happens before called method signature is reviewed.
parent:: syntax is permitted to call base class instance method.
Added "Static" field to meta.FuncInfo to make this check possible.
Re-work of #53
> linter: add callStatic check

- src/linttest/exprtype_test.go
- src/linttest/oop_test.go
- src/solver/solver.go
For ArrayAccess use return type of offsetGet() method.
For Traversable (Iterator, etc.) use return type of current() method.
This behavior is in sync with what PhpStorm does.
> resolve elemOf for ArrayAccess and Traversable

- src/linter/block.go
- src/linttest/oop_test.go
Do it by analyzing new expressions.
If instantiated object class doesn't define __construct method,
check for a method that have the same name as a type name.
Fixes #176
> handle __construct() method call in argCount diagnostic

- src/linter/report.go
- src/linter/root.go
- src/linttest/oop_test.go
PHP5+ code should use __construct() instead.
Fixes #178
> report old-style constructor usages

- src/phpdoc/parser_test.go
The Line and ParamsText fields were added without updating the expected value,
resulting in the test failing.
> Update expected value in phpdoc parser test

- src/linter/block.go
- src/linter/report.go
- src/linter/root.go
- src/linttest/phpdoc_test.go
Split phpdocLint into phpdocLint+phpdocType checks.
> linter: move phpdoc type checks to a separate diagnostic

- example/custom/main.go
Hello @quasilyte , I'm submitting this fix for the issue https://github.com/VKCOM/noverify/issues/189
The output after the fix:
> ✗ go test -v -count 1 ./example/custom/
> === RUN   TestAssignmentAsExpression
> --- PASS: TestAssignmentAsExpression (0.00s)
> PASS
> ok      github.com/VKCOM/noverify/example/custom        0.006s
> Adjusting tests to work with newer php-parser

- src/linter/block.go
Fixes #192 
I removed unused method and const following golangci-lint said
```
$ golangci-lint run --disable-all -E unused
src/langsrv/langsrv.go:74:38: U1000: func `IMessage` is unused (unused)
func writeMessage(message interface{ IMessage() }) error {
^
src/linter/block.go:28:2: U1000: const `loopNone` is unused (unused)
loopNone loopKind = iota
^
src/linter/block.go:128:23: U1000: func `(*BlockWalker).copyContext` is unused (unused)
func (b *BlockWalker) copyContext() *blockContext {
^
```
> Remove unused method and const #192

- src/linter/block.go
- src/linttest/oop_test.go
- src/linttest/trait_test.go
- src/meta/metainfo.go
Don't try to resolve "new self" or "new static" inside the trait context.
Also move trait tests to trait_test.go.
Fixes #182
> linter: don't report undefined class for new self/static inside trait

- src/langsrv/langsrv.go
- src/linttest/exprtype_test.go
- src/linttest/oop_test.go
- src/solver/exprtype.go
- src/solver/solver.go
- src/solver/solver_test.go
Cache version bump in theory may be required if wrong types were cached because of inability to resolve static inside the class before. I am not sure though. If it is required then it is probably very rare.
> Static inside method

- src/linter/block.go
- src/linter/block_context.go
- src/linter/phpdoc_util.go
- src/linter/root.go
- src/linttest/basic_test.go
- src/linttest/exprtype_test.go
- src/linttest/oop_test.go
- src/meta/typesmap.go
- src/solver/exprtype.go
- src/solver/solver.go
- src/solver/solver_test.go
An attempt to improve type inference.
```
Currently, if an expression has type T, it doesn't mean:
"expression always have type T"
it only states that
"expressions might have type T in some cases"
```
So, the function below is believed to return "int" type:
function f($cond) {
if ($cond) { return 10; }
return $cond;
}
The bad part is that it can return a value of type($cond).
The right answer would be `int|type($cond)`, but `int|mixed`
would still be better for now.
- try to fix misspelled types instead of just complaining about them
- make functions/expressions always have type.
When precise type can't be inferred, use void/mixed.
To avoid tons of new allocations, void and mixed type maps are shared
as immutable type maps.
- move returnTypes from block context into the block itself, …
> improve type inference

- src/linter/block.go
- Anonymous classes are not supported yet.
Don't traverse them.
- After parser update "," produce ArrayItem that might be
completely empty (nil val, nil key) and pos is nil as well.
When we try walking these, panic can occur.
This change stops linter from walking them.
> fix panics and false positives

- src/linter/block.go
- src/linter/phpdoc_util.go
- src/linttest/exprtype_test.go
- src/solver/exprtype.go
- src/solver/solver.go
So algorithms that infer array element by stripping [] suffix work
without ad-hoc elemOf("array")=>mixed case.
> resolve array to mixed[]

- src/linter/block.go
This is consistent with root checker.
res only controls whether we enter children nodes, it should
not affect "after enter" callback.
> call AfterEnterNode for block checkers even if res=false

- src/linter/root.go
- src/linttest/phpdoc_test.go
Signed-off-by: Yaroslav Yadrishnikov <y.yadrushnikov@corp.vk.com>
> Handle malformed type-name pairs in @property phpdoc attrs

- src/linter/root.go
- src/linttest/basic_test.go
Should fix #93 
Added `checkFuncArgs` function to check and report argument list syntax (could be expanded later with more checks). It goes after phpdoc checks, but before type inference/checks in `parseFuncArgs`.
Reused blockWalker `handleArray` for checks, which should also warn for duplicate keys etc.
> added syntax check in function definition argument list

- src/linttest/exprtype_test.go
- src/solver/exprtype.go
Previously, they were inferred as "mixed".
> infer unary +/- expression types

- src/langsrv/defs.go
- src/langsrv/langsrv.go
- src/linter/block.go
- src/linter/root.go
- src/meta/metainfo.go
- src/meta/scope.go
- src/meta/typesmap.go
- src/solver/exprtype.go
- src/solver/solver.go
TypesMap is 16 bytes on 64-bit systems (8 on 32-bit), there is
no point in passing it around as a pointer, since we already
have Append-like functions returning a new version of TypesMap objects.
The main benefit is that we don't need to guard against nil TypesMap anymore.
> always use non-ptr version of meta.TypesMap

- src/langsrv/langsrv.go
- src/linter/block.go
- src/linter/root.go
- src/meta/typesmap.go
Some TypesMap.Iterate usages have a pattern of returning early
when they satisfy some predicate. This can be expressed more
elegantly with Find() method, where we have the next advantages:
- Caller can stop traversal with returning "true", no need to
guard against "already found" in the beginning of the callback.
- No sorting is applied, since these tasks don't require
predictable traversal to be deterministic.
> meta: add TypesMap.Find method

- src/linter/cache.go
- src/linter/cache_test.go
We can't compare cache file data reliably right now, since
it contains several gob-encoded maps (they are not sorted).
But we still can compare properties that don't change from
multiple executions and will catch 99% of unexpected cache changes.
Fixes #240
> linter: add cache tests

- src/linter/cache.go
- src/linter/cache_test.go
- src/linter/root.go
- src/meta/typesmap.go
- GodDecode should be a pointer receiver to update a
struct that is being decoded. We still can use non-ptr
TypesMap everywhere, gob will do the right thing
when calling GobDecode even if we have maps of
non-pointer TypesMap.
- Extended TestCache to check for decoded meta correctness
- Added consts to cache test sources.
(We still need to extend the coverage even further.)
- Return nil slice for func params for 0-length param slices.
This is primarily to avoid complications with
serialization/de-serialization testing, since nil
slices are a default zero value.
> linter: fixed a bug in typesmap decoding + added a test

- src/linter/block.go
- src/linter/custom.go
- src/linter/root.go
These methods are only invoked through context that
doesn't need them to be exported.
> linter: unexport some root/block methods

- src/cmd/flags.go
- src/cmd/main.go
- src/linter/block.go
- src/linter/conf.go
- src/linter/custom.go
- src/linter/lintapi/lintapi.go
- src/linter/parser.go
- src/linter/root.go
- src/linter/utils.go
- src/linttest/rules_test.go
- src/phpgrep/LICENSE
- src/phpgrep/README.md
- src/phpgrep/compile.go
- src/phpgrep/doc.go
- src/phpgrep/matcher.go
- src/phpgrep/matcher_test.go
- src/phpgrep/meta_nodes.go
- src/phpgrep/pattern_language.md
- src/phpgrep/phpgrep.go
- src/phpgrep/utils.go
- src/rules/parser.go
- src/rules/rule_kind.go
- src/rules/rules.go
- src/rules/util.go
Added a new command-line argument, -rules=<files-list>.
When this argument is set, NoVerify parses these files
and makes dynamic rules out of it. Dynamic rules are a way
to add diagnostics to NoVerify without a need to write any Go
code or even re-compile the linter.
The rules syntax and matching engine is borrowed from
https://github.com/quasilyte/phpgrep
No measurable performance impact when rules are not used.
When rules are used, we use rule clusterization to
reduce the amount of excessive work performed.
Some more optimizations can be applied later if we find
any bottlenecks or if there is a demand to make this mechanism faster.
Right now it can execute hundreds of rules without significant
penalties (unless all rules belong to the same category,
which can be the case with function …
> all: add dynamic rules support (initial implementation)

- src/linter/root.go
- src/linttest/basic_test.go
Appeared after php parser rewrite. Now Array node represents
both kinds of array literals.
> linter: fix arraySyntax false positive in func params

- src/linter/cache.go
- src/linter/cache_test.go
- src/linter/root.go
- src/linttest/exprtype_test.go
- src/solver/exprtype.go
Previously, class const fetch always resulted in "mixed" type.
Handle ClassConstFetch case in solver to get proper type info for it.
Also use RootWalker.scope() method instead of meta.scope field inside
the walker, since if scope is nil, ExprType would return empty type
resolving results.
> solver: handle ClassConstFetch exprs

- src/linter/cache.go
- src/linter/parser.go
- src/linter/root.go
- src/meta/typestring.go
- src/solver/exprtype.go
- src/solver/solver.go
Running NoVerify on the big open source code corpus
revealed several bugs:
1. GetRootNode now returns *node.Root instead of node.Node,
we assigned that to node.Node vairable and nil check
was broken, causing linter to panic on nil nodes
instead of giving "empty root node" notice.
2. Calling EnterNode on anon class gives a panic,
since class name is nil and we can't set
current class name because of that.
Since a lot of class handling relies on
current class name being available,
skip anon class handling for now by
returning false for these nodes.
This cludge can be removed when #272 is resolved.
3. We can't eagerly resolve ClassConstFetch if
ExprType is called when indexing is incomplete
as it uses FindClass function that depends on meta.Index
being complete. This causes race condition in …
> fix bugs found during php-corpus check

- src/linttest/regression_test.go
- src/phpdoc/parser.go
Even though phpdoc documentation does not explicitly permit
/* @var */ to be used instead of /** @var */, there are
occasions where former form is used. PhpStorm does understand
it, so we can do the same at least by default.
It solves false positives that appear when we miss @var
info due to malformed syntax.
Fixes #289
Fixes #284
> linter: handle /* @var */ in addition to /** @var */

- src/linter/block.go
- src/linter/report.go
- src/linter/root.go
- src/linttest/basic_test.go
Unlike the previous implementation, this one does no
adhoc parsing and uses token positions info instead.
For statements and expressions where the token of
interest is the first token, everything is as simple
as checking string prefix. For tokens like "as" inside
foreach statement, we will need to do something more
intricate, since nothing is saved even inside freefloatings.
We also can't check for end* tokens with this approach.
But all in all, it implements ~90% of checks.
Updates #136
> linter: add keywordCase checker

- src/phpgrep/matcher_test.go
- src/phpgrep/meta_nodes.go
Also removed GetAttributes method from metaNode,
since it's not needed to implement node.Node anymore.
> phpgrep: add call* benchmark for completeness

- src/linter/block.go
- src/linttest/basic_test.go
Outside of foreach loop body, key and value variables
might not be defined (when foreach is executed 0 times).
> linter: better foreach key/val scope handling

- src/linter/root.go
- src/linttest/basic_test.go
- src/linttest/phpdoc_test.go
Warning message borrowed from the PhpStorm inspection.
> linter: check for non-existing var refs in @param

- src/linter/root.go
- src/linter/type_filter_test.go
- src/linter/utils.go
- src/linttest/rules_test.go
- src/meta/typesmap.go
- src/phpdoc/type_parser.go
- src/phpdoc/type_parser_test.go
- src/phpdoc/types.go
- src/rules/parser.go
- src/rules/rules.go
- src/rules/util.go
Changes to @type handling:
- Support for proper union types matching.
- Extend phpdoc package to support types
parsing. Used new types to describe @type
pattern expression from rule files.
- Support of `!<type>` for rules patterns.
A `!<x>` type matches any type, except `<x>`.
Type parser supports intersection types as well
as nullable types, although it's not very useful
for NoVerify right now, we can use them later.
> rules: improve @type filter support

- src/linter/parser.go
- src/linttest/basic_test.go
- src/linttest/rules_test.go
- src/rules/parser.go
- src/rules/rules.go
- src/rules/util.go
Allow a rule to be bound only to some files.
Achieved with `@path $p` filter-like option that requires
a file to contain $p, otherwise, a rule will be disabled for it.
> rules: add @path rule constraint

- src/linter/block.go
- src/linter/cache.go
- src/linter/cache_test.go
- src/linter/root.go
- src/linter/side_effects_finder.go
- src/linter/utils.go
- src/linttest/basic_test.go
- src/linttest/discard_expr_test.go
- src/linttest/exprtype_test.go
- src/linttest/rules_test.go
- src/meta/metainfo.go
- src/meta/typesmap.go
- Add FuncPure flag for functions that are pure-like.
The "pure" definition will be adjusted later,
we need to mark functions that call pure functions
with pure flag as well, but for simplicity,
we don't do deep analysis for now.
- Use FuncPure flag in discardExpr check.
If function/method is pure, its result should
not be ignored (discarded).
- Made several minor changes along the way,
like moved side effects finder to a separate file
and made function call resolving method a
freestanding function to re-use it in
side effects finder.
> all: Pure() function flag

- src/linter/block.go
- src/linter/cache.go
- src/linter/root.go
- src/linttest/exprtype_test.go
- src/meta/typestring.go
- src/phpdoc/parser.go
- src/phpdoc/parser_test.go
> Parse array<K,V>, list<V>, etc as V[]. Currently the key type is ignored

- src/meta/meta_test.go
- src/meta/metainfo.go
Benchstat results:
```
name                 old time/op    new time/op    delta
NameEquals/1part-8     76.2ns ± 2%    15.3ns ± 2%   -79.94%  (p=0.008 n=5+5)
NameEquals/3parts-8     174ns ± 1%      30ns ± 1%   -82.74%  (p=0.008 n=5+5)
name                 old alloc/op   new alloc/op   delta
NameEquals/1part-8      16.0B ± 0%      0.0B       -100.00%  (p=0.008 n=5+5)
NameEquals/3parts-8     48.0B ± 0%      0.0B       -100.00%  (p=0.008 n=5+5)
name                 old allocs/op  new allocs/op  delta
NameEquals/1part-8       1.00 ± 0%      0.00       -100.00%  (p=0.008 n=5+5)
NameEquals/3parts-8      1.00 ± 0%      0.00       -100.00%  (p=0.008 n=5+5)
```
Refs #364
> meta: make NameEquals alloc-free

- src/linter/block.go
- src/linter/block_context.go
- src/linttest/regression_test.go
- src/solver/exprtype.go
- src/solver/node_equal.go
We collect a slice of `<object, methodName>` pairs
inside a block context.
New pair entries are added via `method_exists(object, methodName)`
upon the if statement entry. These entries are removed
upon that if statement exit.
This new addition does not affect the type inference.
We only permit calling method_exists-defined methods,
but their types will be `(...mixed)->mixed`.
Fixes #362
Should be merged after #363 is resolved.
> linter: improve method_exists handling

- src/linter/block.go
- src/linter/root.go
- src/linttest/basic_test.go
- src/linttest/exprtype_test.go
- src/linttest/oop_test.go
Before this fix, ?int was resolved as `?int|null` because
for builtin types we did no classNames[idx] replacement.
Found this while adding more tests to extend test coverage.
It turned out that nullable-related if statement inside
normalizeType() method was not covered by tests.
> linter: fix normalizeType for nullable types

- docs/finding-false-positives.md
The new document explains how to test NoVerify
for false-positives as well as how to fix them.
> docs: add a guide for false-positive hunting

- src/linter/block.go
- src/linttest/regression_test.go
Use andWalker that we're using to handle if statement
conditions to populate ternary expr context for IfTrue branch.
The context is dropped before we walk IfFalse branch, so
only IfTrue branch sees vars added by andWalker.
Fixes #288
> linter: improve handling of conditional ternary expressions

- Gopkg.lock
- src/linter/block.go
- src/linter/parser.go
- src/linter/regexp_utils.go
- src/linter/regexpsimplify.go
- src/linter/regexpvet.go
- src/linter/report.go
- src/linter/root.go
- src/linttest/regexpsimplify_test.go
- src/linttest/regexpvet_test.go
- src/linttest/testdata/ctype/golden.txt
- vendor/github.com/quasilyte/regex/syntax/parser.go
- vendor/github.com/quasilyte/regex/syntax/utils.go
Unlike regexpSimplify, all warnings severity level
is Warning (instead of Maybe).
Uses RE parser mode that merges chars into literals.
> linter: add regexpVet checker

- src/linttest/regression_test.go
- src/php/parser/scanner/lexer.go
- src/php/parser/scanner/scanner_test.go
This is a port of https://github.com/z7zmey/php-parser/commit/6afa2a089b2a9df25d08db76416d1c6ca7119fe8
commit from php-parser upstream repo.
Fixes #327
> php/parser: parse php7-style heredocs/nowdocs correctly

- src/langsrv/defs.go
- src/langsrv/langsrv.go
- src/langsrv/refs.go
- src/langsrv/refsvisitors.go
- src/linter/block.go
- src/linter/side_effects_finder.go
- src/linter/utils.go
- src/linttest/regression_test.go
- src/solver/solver.go
Since traits can't extend or implement anything,
it's 100% guarantee that if we find a symbol inside
a trait it comes from that exact trait.
We can use that to achieve PHP-like semantics of
traits access level.
Suppose we're looking for a symbol S in class C that
uses trait T. Class C doesn't have it so we fall back
into traits. If trait T has S, return it with
implClass=C, so it looks like C itself had it.
That way, we can check accessLevel using the unmodified
canAccess() method.
Fixes #283
Fixes #209
> solver: fix trait members accessLevel issues

- src/linter/block.go
- src/linter/root.go
- src/linttest/basic_test.go
- src/linttest/testdata/parsedown/golden.txt
- src/linttest/testdata/phprocksyd/golden.txt
- src/linttest/testdata/qrcode/golden.txt
- src/linttest/testdata/underscore/golden.txt
```
Before:
UNUSED  unused: Unused variable v
1. Replace UNUSED with INFO in non-LSP mode:
INFO    unused: Unused variable v
2. Re-word message:
INFO    unused: Vairable v is unused
```
Fixes #397
> linter: reduce stutter in unused warnings

- src/cmd/flags.go
- src/cmd/main.go
Use os.UserCacheDir() to find suitable cache dir
if no -cache-dir argument is supplied.
Using -cache-dir='' disables caching.
> cmd: <auto> cache mode

- src/langsrv/langsrv.go
- src/linter/block.go
- src/linter/cache.go
- src/linter/cache_test.go
- src/linter/phpdoc_test.go
- src/linter/phpdoc_util.go
- src/linter/report.go
- src/linter/root.go
- src/linter/side_effects_finder.go
- src/linttest/basic_test.go
- src/linttest/oop_test.go
- src/meta/case_insensitive_map.go
- src/meta/metainfo.go
- src/solver/solver.go
- src/solver/solver_test.go
For every interface in "implements" and class in "extends" run
a method set check.
That check is skipped for abstract classes.
Non-abstract classes must implement every abstract method of their
parents (directly or via traits) and every method from interfaces chain.
Related changes:
- Added FuncAbstract bit to FuncFlags
- solver.FindFunc now correctly prefers concrete method definitions
instead of the closest one.
- Using undefined class in extend/implements clause cause "undefined" error.
Fixes #395
Fixes #368
> linter: add "unimplemented" checker

- src/linttest/testdata/flysystem/golden.txt
- src/linttest/testdata/phprocksyd/golden.txt
- src/linttest/testdata/underscore/golden.txt
Accidentally, strtr function with 2 arguments causes no
warnings after the update. It depends on the definitions
order inside stubs, so #409 still needs to be solved.
> cmd/stubs: update embedded phpstorm stubs

- src/linter/regexpvet.go
- src/linttest/regexpsimplify_test.go
- src/linttest/regexpvet_test.go
*   Improved flag flow checking.
Now it can handle flag clearing.
*   Added checks for dangling/redundant ^.
*   Fix false positive with altAnchors.
> fixes and improvements for regexpVet checker

- src/linter/block.go
- src/linter/report.go
- src/linter/root.go
- src/linter/utils.go
- src/linttest/basic_test.go
- src/linttest/codedup_test.go
- src/php/astutil/astutil.go
- src/php/astutil/nodeSet.go
- src/php/astutil/nodeSet_test.go
NodeSet is a set-like data structure that only has 1 method - Add.
Add either adds an element and returns true or it returns false
if element is already in the set. The complexity is amortized to O(1)
due to the map[string] usage, but creating a map key is somewhat expensive.
There is an optimization for small N to make NodeSet alloc-free.
Moved FmtNode from linter package to astutil to avoid circular deps.
As an example of how we can use NodeSet there is a new dupCond check
that checks switch statement case clauses for duplicated entries.
It's planned to also check if-else chains, but it can wait until we
parse "elseif" and "else if" in the same way.
Refs #365
> add NodeSet type and start implementing dupCond check

- src/linter/block.go
- src/linter/root.go
- src/linttest/basic_test.go
- src/linttest/codedup_test.go
- src/php/astutil/nodeSet.go
- src/php/parser/node/stmt/n_else_if.go
- src/php/parser/node/stmt/n_if.go
- src/php/parser/node/stmt/t_if_test.go
- src/php/parser/php7/php7.go
- src/php/parser/php7/php7.y
- src/php/parser/php7/php7_test.go
- src/php/parser/printer/printer.go
- src/php/parser/printer/printer_parsed_php7_test.go
ElseIf nodes that were created as a product of this merging
have Merged field set to true.
stmt.If.Else.Stmt now should never be stmt.If. All chained
elseifs are pushed to stmt.If.ElseIf slice.
To verify that it's working as intended, dupCond diagnostic is extended
to check for duplicated if/elseif conditions.
Fixes #365
> Parse `} else if { ... }` as `} elseif { ... }`

- src/linter/block.go
- src/linter/report.go
- src/linter/utils.go
- src/linttest/basic_test.go
- src/linttest/codedup_test.go
- src/linttest/regression_test.go
- src/linttest/rules_test.go
- src/meta/typesmap.go
dupBranchBody detects two patterns:
```
1. `if (...) { $x } else { $x }`
2. `... ? $x : $x`
```
dupSubExpr handles most binary operations, except `+`, `*` and` **`.
Some float-typed expressions are excluded from this list (for example, `$x==$x` can be related to a `NaN` check).
> add dupBranchBody and dupSubExpr checks

- src/linter/block.go
- src/php/astutil/astutil.go
Do 5 times less calls to typeExpr() in discardExpr checker.
Achieved by filtering-out non-interesting nodes that should
no be checked anyway. Previously, assignment expressions
were rejected at the very last step when we do side-effects
checking. Since assignments are considered impure, we
did not report them in discardExpr.
Now they're rejected before type solving and side effects calculation.
On the test project it lead to 929336 -> 188471 (5 times decrease)
calls to exprType() in handleStmtExpression().
The distribution of handled nodes in a new code (sum=188471):
```
139362 *expr.FunctionCall
23551 *expr.StaticCall
19517 *expr.MethodCall
3983 *expr.PostInc
441 *expr.PreInc
440 *expr.Print
420 *expr.PostDec
281 *expr.ErrorSuppress
236 *binary.LogicalAnd
118 *expr.PreDec
56 …
```
> optimize discardExpr checker

- src/langsrv/langsrv.go
- src/linter/block.go
- src/linter/parser.go
- src/linter/root.go
- src/linttest/bench_test.go
- src/meta/metainfo.go
- src/meta/scope.go
- src/solver/solver_test.go
Adding a new bool field would require us to add 1 parameter
to every scope function and a call could look like (false, true, false)
which is not very readable. With flags, it can look a little better.
The NoReplace flag is unexported, so the callers from other packages can't set
that flag just as before.
> meta: 2 bools -> 1 flags field

- src/linter/cache.go
We changed the interpretation of scopeVar fields.
Since previous cache change missed version increase as well,
merge both and increase the version by one.
> linter: bump cache version to 37

- src/linter/custom.go
- src/linter/lintapi/lintapi.go
- src/linter/report.go
Behaves like LevelWarning, reported warnings do not contain
a context string or a source code line to avoid sensitive
information leaking to things like CI agent logs, etc.
> linter: add LevelSecurity severity level

- src/linter/block.go
- src/linter/cache.go
- src/linttest/exprtype_test.go
- src/meta/typesmap.go
- src/solver/exprtype.go
The new `TypesMap.IsPrecise()` can be used to determine if
type info is precise enough to perform typecheck-like analysis.
Right now we are quite conservative and create precise types
for language operations that have a predictable result type:
```
- Operators that return a single type in all situations.
We avoid `int|float` operations like `+`, since
the result may depend on how well we infer the
LHS/RHS operand type.
- new() expressions where the class name is known.
```
It's planned to favor the lack of false positives for IsPrecise
rather than false negatives, so some precise types may still
be reported as imprecise and the linter will not perform the
analyzis that requires precise types info.
An example of such analysis is function parameter type checking
and operands type checking. …
> meta: add type precision info to a types map

- src/phpdoc/type_parser.go
- src/phpdoc/type_parser_test.go
> phpdoc: parse "()" as parens with invalid expr

- src/phpdoc/type_parser.go
- src/phpdoc/type_parser_test.go
"@ @" should be parsed as Invalid="@" and rest " @"
should be left as unconsumed input.
> phpdoc: stop parsing invalid expr at whitespace

- src/linter/block.go
- src/linter/phpdoc_util.go
- src/linter/root.go
- src/linttest/exprtype_test.go
- src/phpdoc/parser.go
- src/phpdoc/parser_test.go
- src/phpdoc/type_parser.go
- src/phpdoc/type_parser_test.go
- src/rules/parser.go
phpdoc.Parse now returns a more structured result.
It does handle both `<$var, type>` and `<type, $var>` order
for param/var/property annotations.
Types are parsed with TypeParser, so we don't need to shrink
type strings anymore. It also fixes T{} and T() type expressions
that were not handled by whitespace shrinking code before
(it only handled <> pairs).
Refs #344
> refactor phpdoc parsing

- src/linter/block.go
- src/linter/report.go
- src/linter/utils.go
- src/linttest/basic_test.go
```
A precedence checker detects suspicious expressions
that may behave incorrectly due to the precedence issues.
Right now it only handles & and | with ==/!=/===/!===,
but it may also cover ternary operator patterns in future.
```
> linter: add precedence checker

- src/linter/block.go
- src/linter/report.go
- src/linttest/basic_test.go
`global $superglobal` is redundant and should not be used.
https://www.php.net/manual/en/language.variables.superglobals.php
> linter: add redundantGlobal checker

- src/linter/block.go
- src/linter/phpdoc_test.go
- src/linter/phpdoc_util.go
- src/linter/report.go
- src/linter/root.go
- src/linter/utils.go
- src/linttest/phpdoc_test.go
- src/linttest/testdata/flysystem/golden.txt
phpdocRef is slightly pickier than PhpStorm reference
resolving as it does not permit referencing a type from
another namespace by incorrect relative name.
On the other side, if PhpStorm can't resolve the link,
phpdocRef will give a warning for sure.
The intention is to make it easier to keep @see code
references precise and up to date.
New warnings in flysystem are due to the relative namespace
reference is used: `League\Flysystem\ReadInterface` should be
`\League\Flysystem\ReadInterface` (with leading `\`).
PhpStorm can't resolve this reference either.
> linter: validate @see references

- src/linter/block.go
- src/linttest/basic_test.go
New strictCmp checker suggests using a strict comparison
when comparing something with ==/!= against true/false/null consts.
> linter: report non-strict comparison with true, false and null

- src/linter/types.go
- src/linttest/exprtype_test.go
- src/linttest/shape_test.go
The `tuple` type is a shorthand for `shape` with numerical keys: 
`tuple(T1, T2) = shape{0:T1, 1:T2}`
Fix #436
> linter: add tuple type support

- src/linter/root.go
- src/linttest/rules_test.go
- src/phpgrep/matcher.go
- src/phpgrep/matcher_test.go
- src/phpgrep/phpgrep.go
phpgrep Find() method is recursive.
It tries to match at the top leven, then it traverses
the AST and calls the callback for every matching node.
A new tests (added in this change) resulted in 2 warnings
instead of 1 due to this.
It's not enough to do "return false" to stop the traversal.
To avoid this confusion in future, Find is renamed to FindAll.
A new Find method does not perform any traversal, which is
exactly what we need.
More refactoring can be done later. This change goal
is to fix a bug.
> linter: don't recurse when matching rules

- src/phpgrep/matcher.go
- src/phpgrep/matcher_test.go
- src/phpgrep/tracing_disabled.go
- src/phpgrep/tracing_enabled.go
- src/phpgrep/tracing_test.go
Tracing tests help to understand and evaluate the
execution of the matcher for a given pattern+input pairs.
Tracing is guarded by the build tag so it should not
affect the performance in non-testing builds.
We ignored parsing errors, so some tests were skipped
due to that. Now parsing errors are checked.
> phpgrep: add tracing tests + fix some old tests

- src/linter/parser.go
- src/linter/root.go
- src/phpgrep/compile.go
- src/phpgrep/matcher.go
- src/phpgrep/matcher_test.go
- src/phpgrep/phpgrep.go
- src/phpgrep/tracing_test.go
- src/phpgrep/utils.go
```
All mutable state is now passed explicitly through
the matcher methods. This way we can decouple readonly
shared state (fields inside the matcher) and state
that needs to be changed during the matching.
Since most patterns have 0-3 variables, a slice
with linear search is a viable alternative to a map.
It's easier to re-use memory and make less
allocations with a slice.
Numbers below show the performance difference where "old"
is a map-based solution and "new" is based on slices.
name                              old time/op    new time/op    delta
Find/positive/call_parent_ctor-8     273ns ± 2%     156ns ± 1%   -42.90%  (p=0.008 n=5+5)
Find/negative/call_parent_ctor-8    86.0ns ± 3%    13.8ns ± 1%   -83.96%  (p=0.008 n=5+5)
Find/negative/const-tail-8           811ns ± 2%     658ns ± …
```
> phpgrep: make matcher faster and thread safe

- src/linter/block.go
- src/linter/report.go
- src/linter/root.go
- src/linttest/oop_test.go
parentConstructor reports __construct() methods that
do not call parent::__construct() when they need to do so.
We require a parent constructor call if a class extends
the other class that has a explicitly defined constructor
(which is callable from the derived class).
Fixes #408
> linter: add parentConstructor checker

- src/linter/side_effects_finder.go
Some functions come from the top-100 frequently called
list, some functions were just easy to add (like predicates
and type converting functions).
> linter: mark more builtin funcs as pure

- src/linter/custom.go
This way, external checkers don't need to share
the types parser directly.
> linter: add ParsePHPDoc method to RootContext

- src/linter/block.go
- src/linter/root.go
- src/meta/typesmap.go
1. Parameter default value is not a precise source.
2. Static variables should be skipped as their assignment
is only executed once (type can change after another assignment).
> linter: add 2 exceptions to type precision inference

- src/linter/custom.go
- src/linter/utils.go
- src/linttest/exprtype_test.go
- src/solver/exprtype.go
```
Summary:
- Re-written all exprtype tests (see below).
- Used ResolveTypes in ExprType because we had
a code duplication there that did not handle empty_array.
- Added ExprType() method to make it easier for custom
checkers to evaluate the expression type.
How exprtype tests worked before:
For every test expression we generated a function
that performed `return expr`. Then we were
comparing function inferred return type with
expected type. The problem is, this approach
does not allow us to test ExprType() function
in arbitrary context. A simple example is that
we can't test global scope type resolving.
New approach:
Instead of having a separate test cases,
a special exprtype($expr, $typestring) calls
are expected to be used.
That function can be placed anywhere inside
a code that is …
```
> improve exprtype tests

- src/linttest/exprtype_test.go
- src/meta/scope.go
- src/meta/typesmap.go
```
Append(n TypesMap) case for mutable maps had no
checks for the precision. This made mutable maps
keep precision bit even if the imprecise map was appended.
We mark all mutable maps that are being appended
to as imprecise because we're lacking a good control
flow support (several open issues with how we deal with
if statements, etc.) and exprtype tests are not
exhaustive on the type precision yet.
More investigation is needed.
exprtype tests were fixed along the way.
If typesmap comes from a *scope.Var and it happens
to be mutable, it can change over the course of
the analysis. We need to do a Clone() to avoid that.
Note that TypesMap.Immutable() is not enough as it
only works if the map ownership was transferred.
In our case, it's not true as *scope.Var is still
the owner and this may …
```
> meta: fix precision issue for mutable type maps

- src/linter/cache.go
On windows platform, when I run with "langsrv", the file path is lowercase for driver letter
> linter: Fixed cache name sensitive on windows platform

- src/cmd/main.go
Run() is like Main(), but it returns <int,error>
instead of doing log.Fatal()/os.Exit().
Fixes #490
> cmd: add Run() function

- src/cmd/git_main.go
- src/cmd/main.go
- src/langsrv/langsrv.go
- src/linter/parser.go
- src/linttest/exprtype_test.go
- src/meta/metainfo.go
meta.InitStubs() sets stubs loading flag to true in the beginning
and to false before it returns.
Minor issue fix: git_main now uses embedded stubs when
executed with gitFullDiff=true.
Fixes #493
> all: add meta.IsLoadingStubs and use meta.InitStubs everywhere

- src/linttest/exprtype_test.go
- src/linttest/regression_test.go
- src/phpdoc/parser.go
- src/phpdoc/parser_test.go
Since there can be multiple type annotations in a phpdoc
block, we need to do a Type.Clone() to avoid previously
parsed types corruption.
We could avoid that if we were processing phpdoc
directives one-by-one in a stream fashion, but since
we're eagerly converting all directives to a slice,
we can't avoid these allocations.
Fixes #497
> phpdoc: fix phpdoc.Parse()

- src/cmd/conf.go
- src/cmd/git_main.go
- src/cmd/main.go
- src/linter/report.go
This allows a custom NoVerify-based tool to examine all
reports before they are printed.
Another use case is a custom reports filtering.
> cmd: add MainConfig.BeforeReport hook

- Makefile
- src/linttest/golden_test.go
- src/linttest/linttest.go
- src/linttest/testdata/flysystem/golden.txt
In our tests we don't do concurrent indexing/linting which
makes it harder to catch undesired processing order dependencies.
With randomized indexing/linting we're getting closer to the
real world cases where order of parsing is not guaranteed to
be the same between executions.
Test failure prints a seed that was used.
Using that value with `$TEST_SEED` environment variable
makes it possible to easily reproduce the failing state.
> linttest: shuffle PHP input files

- src/linter/block.go
- src/linter/report.go
- src/linttest/regression_test.go
- src/linttest/rules_test.go
#406
Added checks for non-public methods and constants in interfaces.
Example:
```php
interface WithConstants {
const r = 10000; // ok
public const v = 1; // ok
private const b = 100, c1 = 1000; // 'b' can't be private, 'c1' can't be private
protected const c = 100; // 'c' can't be protected
}
interface WithMethods {
public function c(); // ok
private function b(); // 'b' can't be private
protected function f(); // 'f' can't be protected
}
interface WithStaticMethods {
static function f1(); // ok
public static function f2(); // ok
private static function bad1(); // 'bad1' can't be private
static protected function bad2(); // 'bad2' can't be protected
}
interface WithoutAnyModifier {
function f(); // Ok,
}
```
No warnings.
```
<critical> WARNING nonPublicInterfaceMember: 'b' can't be …
```
> Added report for illegal non-public interface methods and constants

- src/cmd/flags.go
- src/cmd/git_main.go
- src/cmd/linter_runner.go
- src/cmd/main.go
- src/linttest/golden_test.go
It's a small step, but it's better to do it now than never.
The first benefit that we get is that now it's obvious that
every InitEmbeddedRules call from the linttest package also
modified cmd package global state. It's not an error, but
it's not a pleasant side effect.
The next step would be to turn all linter.* vars from the
config.go file into a struct that would them and pass it
to the root walkers.
Updates #523
> cmd: replace the global flag vars with an explicit context

- src/cmd/linter_runner.go
initCheckMappings() should be called before initRules().
> cmd: fix linter init order

- src/cmd/flags.go
- src/cmd/git_main.go
- src/cmd/linter_runner.go
Code was assigning to a wrong field so git.Zero was not replaced
by the "master" string. This led to a panic that is quite hard to
reproduce outside of the real-world environment.
To make this mistake less likely in future, I removed fields
from the struct and store these values as local values as they're
only needed inside that function scope.
gitRef looks unused. It was unused before the refactoring as well.
Maybe it was used before but we broke something a long time ago?
This calls for another investigation.
Refs #513
> cmd: fix git mode for the gitRepoComputeReportsFromCommits() case

- src/linttest/exprtype_test.go
- src/linttest/trait_test.go
- src/solver/solver.go
When `self` is used inside a trait T, we expand that `self` to T
during the indexing phase (so metadata contains T instead of `self`).
This is not correct as T can't be a valid type on its own and `self`
always refers to a class C that embeds T.
Since T is not a valid type name, but it's known to be a trait name,
we can safely replace T with C during the types solving.
In contrast to the late static bindings resolution, we do that
replacement right away using the current scope className.
I also fixed a bug in WStaticPropertyFetch case. It was passing
class variable instead of className down the resolution chain
which led to invalid late static binding results.
Fixes #533
> solver: improve `self` handling in traits

- src/cmd/flags.go
- src/cmd/git_main.go
Modify cmdline args for now and read these 2 values from there.
Code can be cleaned up further when we have at least some
ways to verify git mode correctness without manual testing.
Does this change fix all problems now? Who knows! :(
> cmd: (maybe) fix gitCommitFrom and gitCommitTo issue

- example/custom/main.go
- src/cmd/conf.go
- src/cmd/main.go
- src/cmd/rules.go
- src/rules/rules.go
To avoid doing the double work, pass some information
to the custom linters explicitly.
Right now I only need rule sets, but we may need something
else in the future.
> cmd: pass InitEnvironment object to AfterFlagsParse

- src/phpdoc/exprkind_string.go
- src/phpdoc/type_parser.go
- src/phpdoc/type_parser_test.go
Refs #537
I also fixed the precedence issue so the `?Foo<B>` is parsed as a nullable generic type.
> phpdoc: support parsing of typed callable types

- src/linter/block_context.go
- src/linttest/testdata/embeddedrules/file.php
- src/linttest/testdata/embeddedrules/golden.txt
- src/linttest/testdata/idn/golden.txt
- src/php/astutil/astutil.go
- src/php/astutil/equal.go
- src/php/parser/node/expr/n_paren.go
- src/php/parser/node/expr/t_clone_test.go
- src/php/parser/node/expr/t_paren_test.go
- src/php/parser/node/expr/t_print_test.go
- src/php/parser/node/stmt/t_echo_test.go
- src/php/parser/node/stmt/t_while_break_test.go
- src/php/parser/php7/php7.go
- src/php/parser/php7/php7.y
- src/php/parser/php7/php7_test.go
- src/php/parser/printer/pretty_printer.go
- src/php/parser/printer/printer.go
- src/php/parser/scanner/scanner_test.go
- src/phpgrep/matcher.go
- src/phpgrep/matcher_test.go
- src/solver/exprtype.go
This change introduces a new AST node - paren expr.
There is a chance that we'll need to adjust some places
to be aware of parens, but I think this is a good first step.
Fixes #540
> php/parser: parse ($x) as expr.Paren

- src/linter/side_effects_finder.go
- src/linttest/regression_test.go
Since we can get both FQN and relative names, it's more
reliable to do a proper function name resolving in
side effects finder.
We only handled relative names before which led to false
positives in discardExpr when FQN was used.
Fixes #547
> linter: fix function name resolving in side effects finder

- src/langsrv/langsrv.go
- src/linttest/exprtype_test.go
- src/solver/exprtype.go
- src/solver/solver.go
- src/solver/solver_test.go
We achieve this by using map[string]map[string]struct{} instead of
map[string]struct{}. The nested maps are the resolveType results for
a given type.
We start by assigning a nil map so we don't fall into the infinite
recursion. When resolveTypeNoLateStaticBinding returns we record
resolving results into the same map key. If we hit the resolving loop,
we return previously computed value (if any).
This does affect the performance by a ~5%:
name                     old time/op    new time/op    delta
ExprType/simplevar-8       2.15µs ± 2%    2.27µs ± 1%  +5.43%  (p=0.008 n=5+5)
ExprType/f1call-8          5.06µs ± 1%    5.22µs ± 1%  +3.23%  (p=0.008 n=5+5)
ExprType/f3call-8          3.78µs ± 1%    3.92µs ± 2%  +3.49%  (p=0.008 n=5+5)
ExprType/m4call-8          7.22µs ± 2%    7.52µs ± 1% …
> solver: return prev solving result for recursive cases

- src/linter/block.go
- src/linttest/regression_test.go
When doing a method/property lookup to see whether it's defined,
don't stop at the first name match. We may find a more accessible
version of the symbol. Right now we prioritize own symbols over
base class symbols over everything else.
Fixes #548
> linter: don't stop at the first method/prop match

- src/linttest/regression_test.go
- src/solver/solver.go
Added 2 cases:
- Implements(I, I) => true
- Implements(I1 extends I2, I2) => true
We could separate the loop for class-only and interface-only paths,
but it seems we can't tell whether a ClassInfo represents
a class or an interface.
Fixes #556
> solver: handle interfaces in Implements()

- src/linttest/indexing_order_test.go
- src/meta/metainfo.go
Like with functions, choose a "larger" definition.
This makes the linter output more stable as traversal
order will not influence indexing results.
We still may want to store slices of entries instead of only
one, but that's a bigger task and would require much more changes.
Output stability is required to make the baseline mode usable.
> meta: handle class and trait collisions

- src/cmd/flags.go
- src/linter/conf.go
Removed linter.DefaultEncoding global var as it's unused.
> cmd: deprecate -encoding flag

- src/cmd/main.go
Suppose we have 2 source folders: `www` and `cron`. They use classes from `vendor`. We want to check `www` and `cron`, but we also need definitions from the `vendor`.
It can be simple with index-only-files:
noverify -index-only-files ./vendor ./www ./cron
If we don't have -index-only-files, then we have to do this:
noverify -exclude vendor ./www ./cron ./vendor
Or this (a better way, but requires arguments duplication):
noverify -full-analysis-files ./www,./cron ./www ./cron ./vendor
With index-only-files we can specify source directories that are
required for the indexing phase, but should not be visited during the
linting phase.
> cmd: handle index-only-files flag in non-git mode as well

- src/baseline/baseline.go
- src/baseline/baseline_test.go
- src/cmd/main.go
This makes it easier to figure out which profile is older
or newer (especially if the linter version string is identical).
> baseline: store creation date inside the profile

- src/lintdoc/lintdoc.go
- src/lintdoc/lintdoc_test.go
- src/linter/custom.go
- src/linter/report.go
linter.CheckerInfo gets 2 new fields: Before and After.
Before is a non-compliant code example (before the fix).
After is a compliant code example (after the fix).
A new package, lintdoc, provides utilities to render
check info in a human-readable format. It's meant to be
used in NoVerify as well is in custom NoVerify-based tools
that want to work with checks metadata.
Fixes #579 
> linter: add compliant/non-compliant code examples for every checker doc

- src/linter/block.go
We can't use solver.GetConstant during the indexing phase, otherwise
a race condition will occur: some goroutines update meta.Info,
some other read meta.Info, without synchronization.
Our current solution is to add IsIndexingComplete guards and avoid
code paths that are unsafe for index+linting phase execution.
We may separate both code paths completely in future.
> linter: fix concurrent map access read/write (via solver.GetConstant)

- src/linter/block.go
- src/linter/cache_test.go
- src/meta/encoding_test.go
- src/meta/metainfo.go
The way of storing values for constants has been changed. Now interface{} is used for this, which avoids unnecessary conversions from a string to a certain type and back.
Since the data is not stored in a string, methods for decoding and encoding and tests for them were written for caching.
Solve #594
> Improved storage of the value of constants

- .gitignore
- src/cmd/flags.go
- src/cmd/linter_runner.go
- src/cmd/main.go
- src/linter/custom.go
- src/linter/report.go
- src/linter/root.go
- src/linttest/basic_test.go
- src/linttest/golden_test.go
- src/linttest/linttest.go
- src/linttest/rules_test.go
Some refactoring was required in order to make the work easier.
linter.Report structure now exports all its fields to
make it possible to write report formatting function
outside of the linter package.
The new flag -allow-all-checks is used in e2e tests to enable
all checkers without a need to enumerate all of them.
How end-to-end tests is implemented:
- If all golden tests pass, we run all of them again,
but using the NoVerify binary that will be compiled
as a part of the test.
- When -short flag is specified, e2e tests are skipped
to reduce the time required to pass all tests.
- NoVerify binary is compiled with -race flag. It makes
it run noticeably slower, but we get a chance to catch
some race conditions during the testing.
Plans for the future:
- Test with cache as well.
- Add …
> linttest: add e2e layer to golden tests

- src/linter/root.go
If some rule sets a value for `@fix`, then a situation may arise that when replacing a string truncated to 60 characters will be placed, which will lead to syntax errors.
Therefore, for output to the console, if the proposed fix is longer than 60 characters, it is truncated, but in case of a fix it remains the original.
Fixes #598
> linter: ignoring the maximum length for suggestions

- src/linter/block.go
- src/linter/root.go
- src/solver/side_effects.go
This way it's easier to reuse this code.
sideEffectFree function was unexported in linter package.
Since linter package already contains too much symbols, it's probably better to move it to solver package (at least for now).
> linter: move sideEffectFree function to solver package

- src/tests/golden/golden_test.go
From docs:
> The per-goroutine memory access history is 32K * 2**history_size elements.
Increasing this value can avoid a "failed to restore the stack"
error in reports, at the cost of increased memory usage.
We have "failed to restore the stack" in #614 so it's useful for us already
to reveal the full stack trace.
See https://github.com/golang/go/issues/10661
> tests/golden: use GORACE to increase history_size

- src/linter/root.go
This helps to avoid races in #614
> linter: save shape type props types as immutable type maps

- src/linter/block.go
- src/tests/exprtype/exprtype_test.go
Added type inference for each variable when destructuring a variable with the `\tuple` type or a function that returns `\tuple`.
Added test.
For example:
```php
class Boo {}
/**
* @return \tuple(int, \Boo, int, string)
*/
function foo() {
return [5, new Boo(), 10, "gas"];
}
$tuple = foo();
[$i, $bo, $j, $str] = $tuple;
exprtype($i, "int");
exprtype($bo, "\Boo");
exprtype($j, "int");
exprtype($str, "string");
```
> Infer types in list() over tuple

- src/php/parser/printer/pretty_printer.go
> php/parser/printer: do not mutate node.Root when printing

- src/linter/block.go
- src/linter/custom.go
- src/linter/nodepath.go
- src/linter/parser.go
- src/linter/root.go
- src/tests/custom/path_test.go
For every visited node, push it to the node path.
Pop node when we leave the node.
If EnterNode() returns false, we need to do a pop
since LeaveNode() will not be called in that case.
Where we can use it?
- Get current node parent.
- Find whether this node is an argument of specific func call.
- Find whether this node located under if/for/etc.
> linter: collect and expose AST node path

- src/linttest/linttest.go
If <?php tag was forgotten, test will never result in any
warnings as it will be parsed as inline HTML.
This change adds a sanity check that helps to detect such mistakes
as early as possible.
> linttest: check for <?php tag in SimpleNegativeTest arg

- src/linter/block.go
- src/linter/parser.go
- src/linter/report.go
- src/linter/root.go
- src/tests/checkers/basic_test.go
Finds global statements over repeated variables.
Using the same name inside one statement emits a warning-level report.
Redundant global between statements produces maybe-level report.
We only track unconditional global statements for inter-statement analysis.
> linter: add dupGlobal checker

- src/linter/block.go
- src/linter/report.go
- src/tests/checkers/basic_test.go
Reports potential integer overflows that may result in unexpected behavior.
See https://bugs.php.net/bug.php?id=53934
Fixes #623
> linter: add intOverflow check

- src/tests/checkers/basic_test.go
- src/tests/checkers/regression_test.go
- src/tests/checkers/rules_test.go
- src/tests/exprtype/exprtype_test.go
Due to the introduction of default stubs
> linttest: removed unnecessary definitions of functions and constants in tests

- src/linttest/linttest.go
With this, we can finally see the corrent filename in
failed test output.
Instead of this:
--- FAIL: TestVoidResultUsedInAssignment (0.01s)
linttest.go:144: unexpected number of reports: expected 1, got 0
linttest.go:173: pattern 0 matched nothing: void function result used
linttest.go:178: >>> issues reported:
linttest.go:182: <<<
We get this:
--- FAIL: TestVoidResultUsedInAssignment (0.01s)
basic_test.go:489: unexpected number of reports: expected 1, got 0
basic_test.go:489: pattern 0 matched nothing: void function result used
basic_test.go:489: >>> issues reported:
basic_test.go:489: <<<
basic_test.go is an actual file with the test and line=489 is a
line that executed the test itself.
> linttest: use t.Helper() to skip irrelevant funcs

- src/linter/and_walker.go
- src/linter/block.go
- src/linter/block_linter.go
- src/linter/block_utils.go
- src/linter/parser.go
- src/linter/root.go
- src/tests/golden/testdata/idn/golden.txt
- src/tests/golden/testdata/underscore/golden.txt
As a first step, we move some simple checks to the
blockLinter type that runs only on linting phase
(so it doesn't have to guard against IsIndexingComplete).
There are some checks that are hard to be separated from
the walker, but it's a matter of time until we get to them.
As of now, new checks should be first attempted to be implemented
in blockLinter.
Additional changes to make block.go file smaller:
* andWalker type goes to the separate file (and_walker.go)
* some methods became functions and moved to block_utils.go
Changes in golden test are due to the different reports order
after the refactoring.
> linter: start linting and indexing separation

- src/linter/root.go
This issue arises only in dynamic rules.
> linter: fix issue with unintended formatting

- src/linter/root.go
- src/tests/checkers/oop_test.go
- src/tests/checkers/regression_test.go
Fixed errors in tests (`TestNonPublicMagicMethods`, `TestIssue8`) that appeared due to a new check.
> linter: added check for the correct number of arguments for magic methods

- src/ir/irfmt/printer.go
Change param type from Node to the concrete type
and avoid the need to do the type assertion inside
every node printing method.
(I was a fool to do this refactoring manually.)
> ir/irfmt: remove redundant type assertions

- src/ir/freefloating.go
- src/ir/get_node_kind.go
- src/ir/get_position.go
- src/ir/irfmt/printer.go
- src/ir/irfmt/printer_test.go
- src/ir/irutil/clone.go
- src/ir/irutil/equal.go
- src/ir/types.go
- src/ir/walk.go
- src/irgen/irgen.go
- src/linter/block_linter.go
- src/phpgrep/matcher.go
- src/solver/exprtype.go
It seems like this is a worthwhile simplification.
Only one place becomes more complex (solver exprtype) while
all other usages become better.
Unset cast is not merged into TypeCastExpr as it's very special
and should not be handled in combination with type casts.
> ir: merge type cast expressions into TypeCastExpr

- src/irgen/irgen.go
This will be useful later to resolve relative namespace
nodes into the FQN. We'll store current namespace inside
the convState object.
> irgen: pass explicit convertion state

- example/custom/main.go
- src/ir/freefloating.go
- src/ir/get_node_kind.go
- src/ir/get_position.go
- src/ir/irfmt/printer.go
- src/ir/irfmt/printer_test.go
- src/ir/irutil/clone.go
- src/ir/irutil/equal.go
- src/ir/methods.go
- src/ir/types.go
- src/ir/walk.go
- src/irgen/irgen.go
- src/linter/and_walker.go
- src/linter/block.go
- src/linter/block_linter.go
- src/linter/root.go
- src/phpgrep/matcher.go
- src/solver/exprtype.go
- src/tests/exprtype/exprtype_test.go
This is done to simplify arguments handling.
We can't store arguments as []*Argument since it will
require us to duplicate code that accepts []Node
(and we don't have generics yet).
As a workaround, all nodes with arguments get Arg(i) method
that returns ith argument type-asserted to *Argument.
So we can do:
call.Arg(i)
Instead of:
call.ArgumentList.Arguments[i].(*ir.Argument)
This does look like an improvement.
To avoid information loss, freefloating from the ArgumentList
is stored inside the call-like node itself. So if we ever
need it, it's there.
> ir: simplify argument lists (and remove ArgumentList node)

- src/ir/irconv/irconv.go
- src/ir/irconv/utils.go
- src/langsrv/langsrv.go
- src/langsrv/refs.go
- src/linter/parser.go
- src/phpgrep/compile.go
- src/phpgrep/matcher_test.go
- src/rules/parser.go
We may have irgen package later that generates IR-related code.
The ir/irconv package does not generate anything, it converts
php-parser AST into our own IR.
> irgen: rename to ir/irconv

- src/linter/block.go
- src/tests/exprtype/exprtype_test.go
Added type inference for each variable when destructuring variable with the `\shape` type or function that returns `\shape`.
For example:
```php
/** @return shape(key:\Foo, key2:float, key3:int) */
function asShapeWithStringKey() { return []; }
function foo() {
["key" => $a, "key2" => $b, "key3" => $c] = asShapeWithStringKey();
exprtype($a, "\Foo");
exprtype($b, "float");
exprtype($c, "int");
}
```
> linter: infer types in list() over shape

- src/cmd/flags.go
- src/cmd/git_main.go
- src/cmd/linter_runner.go
- src/cmd/main.go
- src/langsrv/langsrv.go
- src/langsrv/refs.go
- src/linter/conf.go
- src/linter/parser.go
- src/tests/exprtype/exprtype_test.go
- src/workspace/filename_filter.go
- src/workspace/files.go
- src/workspace/git_files.go
The FS traversal does not depend on the linter package
details, so we can move it somewhere else.
workspace package is intended to be used as a toolbox
for working with the PHP project (its files, settings, etc).
> linter: move dirwalk-related code to workspace pkg

- src/ir/irfmt/printer.go
- src/ir/irfmt/printer_test.go
This is consistent with what we had before the IR transition.
> ir/irfmt: print new expr without () if Args==nil

- src/ir/irutil/inspect.go
Works in the same way as go/ast.Inspect().
> irutil: add Inspect function

- src/ir/irutil/irtutil.go
- src/linter/and_walker.go
- src/linter/block.go
- src/linter/block_linter.go
- src/linter/cache.go
- src/linter/cache_test.go
- src/linter/regexp_utils.go
- src/linter/report.go
- src/meta/metainfo.go
- src/tests/checkers/basic_test.go
Since we used strconv.Unquote, ""-literal quotes were
removed while ''-literals were stored with double pairs of quotes.
This can be fixed with our own unquote function.
As we need that unquote in more than 1 package, it was moved
to irutil package.
To avoid quotes confusion in future, we start storing string values
without quotes in meta. Since we store type tag, we don't need
quotes to determine the value kind during decoding.
> meta: fix string const value for ''-literals

- src/linter/cache_test.go
- src/linter/root.go
- src/meta/const_value.go
- src/meta/metainfo.go
- src/solver/const_value.go
- src/solver/exprtype.go
Move const defs and functions to a separate files.
Get rid of -1 multiplier hack to handle unary minus.
> solver,meta: refactor const-related code

- src/ir/irconv/irconv.go
Fixed bug where slice of class modifiers had zero length but not nil, which led to an unnecessary space before the word "class".
> ir/irconv: fixed unnecessary space before the word "class" in printer

- src/linter/block_linter.go
- src/linter/root.go
- src/tests/checkers/basic_test.go
Print both duplicated key syntax (as in the source file) and value,
but do not print the value if it's identical to the syntax string.
Since ir.String can contain non-printable chars like \n, we print
values with %q, so \n will be displayed as "\n" and will not end
up creating an actual newline in the output.
> linter: improve dup array key messages

- src/ir/irconv/utils.go
Escape values are never negative.
> irconv: use ParseUint instead of ParseInt to handle escapes

- src/constfold/eval.go
We don't need to unquote ir.String anymore.
> constfold: remove unnecessary unquote which led to a panic

- src/linter/root.go
Now that it's easier to convert to and from ir.Name,
we can avoid unnecessary code duplication more easily.
> linter: implement expandName with solver.GetClassName

- src/constfold/eval.go
- src/ir/normalize/normalize.go
- src/ir/normalize/normalize_test.go
* All list-assignments become keyed.
* Class constants are folded like normal constants.
> ir/normalize: add list and class const normalization rules

- src/linter/block.go
Let there be 1 less place where we append to the unusedVars slice.
> linter: remove code duplication by using trackVarName 1 more time

- .gitignore
- src/tests/golden/golden_test.go
This change makes e2e tests finish ~20% faster.
In order to make parallel execution possible, all tests
write to a different output file.
> tests/golden: execute e2e tests in parallel

- src/linter/block.go
- src/tests/custom/path_test.go
We don't call Walk() on catch stmt, so ir.CatchStmt never
gets into the node path. This makes Conditional() never
return true for ir.CatchStmt case.
> linter: fix node path for catch stmt

- src/linter/block.go
- src/meta/metainfo.go
- src/meta/typesmap.go
- src/solver/solver.go
So we don't duplicate `strings.HasPrefix(t, "\\shape$")` everywhere.
This is not the best solution as we could use something more
typed that just a string, but it's OK for now.
> meta: add some type string predicates

- src/linter/block.go
- src/linter/root.go
- src/tests/checkers/basic_test.go
- src/tests/checkers/paramClobber_test.go
Finds cases where function/method param is overwritten
before being used.
We give up if we encounter func_get_args() as there is
a pattern where named arguments are replaced with
func_get_args elements, like so:
```php
function f($x, $y) {
$args = func_get_args();
$x = $args[0];
$y = $args[1];
// ...
}
```
> linter: add paramClobber checker

- src/linter/block.go
- src/tests/exprtype/exprtype_test.go
To avoid types map allocation in every foreach statement,
we'll use a global immutable `int|string` types map for this.
This particular types information is useful for warning
messages, so the user gets {int|string}->method instead of
{mixed}->method and it will be easier to see that the
linter does infer the types and it's not a false positive.
> linter: assume int|string array key types in foreach stmt

- src/linter/parser.go
- src/linter/worker.go
That pool is used inside worker, so it belongs to the
worker.go file, not parser.go file.
> linter: move bytes pool to worker.go

- src/cmd/php-guru/dupcode/main.go
- src/ir/irconv/irconv.go
- src/ir/irfmt/printer_test.go
- src/ir/normalize/normalize_test.go
- src/langsrv/langsrv.go
- src/langsrv/refs.go
- src/linter/worker.go
- src/phpgrep/compile.go
- src/phpgrep/matcher_test.go
- src/rules/parser.go
Introduce the Converter object that will be used everywhere
where we want to do AST->IR.
The benefit is that we can clearly see where that converter
can be reused and where it can be used as a one-off object.
The ConvertRoot and ConvertNode functions are removed
to avoid API duplication.
> ir/irconv: do AST->IR via converter API

- src/linter/worker.go
For the big PHP corpus, regexp parser creation can be an expensive operation.
From the memory profile (analyzing Moodle):
347.32MB  1.16% 77.41%   347.32MB  1.16%  github.com/quasilyte/regex/syntax.newParser
If we re-use worker parsers, this issue goes away.
> linter: re-use regexp parsers on worker level

- src/linter/root.go
> linter: don't compute the report hash if baseline is not enabled

- src/baseline/baseline.go
- src/baseline/baseline_test.go
- src/linter/root.go
- src/linter/worker_context.go
With this trick, we get rid of all hash computation
related allocations. workerContext.scratchBuf can
be used anywhere where we need a buffer for tmp results.
Fixes #727
> baseline: use externally provided scratch buffer

- src/ir/irutil/clone.go
- src/ir/irutil/codegen.go
- src/ir/irutil/equal.go
This bug is a consequence of the AST->IR transition.
It doesn't make code incorrect, but we generated more
code than we could.
> ir/irutil: fix codegen for node slices

- src/ir/freefloating.go
- src/ir/helper_types.go
- src/ir/irconv/irconv.go
- src/ir/irfmt/printer.go
- src/ir/irfmt/printer_test.go
- src/ir/irutil/clone.go
- src/ir/irutil/codegen.go
- src/ir/irutil/equal.go
- src/ir/irutil/irtutil.go
- src/ir/methods.go
- src/ir/types.go
- src/ir/walk.go
- src/linter/block.go
- src/linter/block_linter.go
- src/linter/root.go
- src/phpgrep/matcher.go
- src/tests/regression/pull236_test.go
Instead of having ClassStmt node for both normal class
declarations and anon class expressions, make ClassStmt
relevant only for class declarations and new AnonClassExpr
for anonymous class expressions.
I tried to update the code that could be affected by this,
but we don't have enough tests with anon classes unfortunately.
See #732
> ir: introduce AnonClassExpr node

- src/ir/codegen/gen_clone.go
- src/ir/irutil/clone.go
If lhs type is ir.Node, don't generate the redundant
rhs.(ir.Node) type assertion.
Fixes #749
> ir/codegen: don't generate redundant I->I for Clone()

- src/ir/irconv/irconv.go
- src/ir/irutil/clone.go
- src/ir/node_types.go
We can't specialize []Node to []*Name as it would break all
the code that expects []Node in algorithms (like phpgrep and
dynamic rules). We should either wait for generics there or
use codegen even more.
> ir: ClassExtendsStmt.Name :: Node -> *Name

- src/linter/block.go
- src/solver/exprtype.go
- src/tests/exprtype/exprtype_test.go
Since these operators always return the precise type,
it's a low hanging fruit for us.
> solver: add .= <<= >== assignments type inference

- src/linter/phpdoc_test.go
- src/linter/root.go
- src/linter/utils.go
- src/rules/typematch.go
- src/rules/typematch_test.go
This code is used in rules-related linter branch,
so it makes sense to move it to the rules package.
> linter,rules: move type matching code to rules

- src/rules/typematch.go
- src/rules/typematch_test.go
- src/tests/golden/testdata/embeddedrules/ternarySimplify.php
Instead of adding a new type filter, make the default type
filter work in a more predictable way.
We can handle both (1) and (2) cases described in the #753
with the proposed approach.
Refs #753
> rules: improve type matching rules

- src/tests/rules/rules_test.go
> tests/rules: add t.Helper() call to runRulesTest

- src/tests/golden/testdata/embeddedrules/assignOp.php
- src/tests/golden/testdata/embeddedrules/golden.txt
With functions per test we don't overwrite the
variable types which can lead to the unrelated checks
reporting this code.
> tests/golden: improve assignOp tests

- src/cmd/rules.go
Due to the `break` instead of `continue` inside the filtering
loop we disabled all rules from the category if any of the rules
are rejected by the -allow-checks flag.
> cmd: fix -allow-checks filtering of rules

- src/linter/block.go
- src/tests/exprtype/exprtype_test.go
- src/tests/golden/testdata/underscore/golden.txt
Like PhpStorm, collect all array types and assign a union
type of all element types to the list variables.
$xs = [1, 2];
list ($a, $b) = $xs;
// $a is int
// $b is int
This way we get more types information.
> linter: improve list(...)=$a type inference for arrays

- src/ir/freefloating.go
- src/ir/get_node_kind.go
- src/ir/get_position.go
- src/ir/irconv/irconv.go
- src/ir/irconv/irconv_test.go
- src/ir/irconv/utils.go
- src/ir/irutil/clone.go
- src/ir/irutil/equal.go
- src/ir/node_types.go
- src/ir/walk.go
- src/linter/block_linter.go
- src/tests/checkers/basic_test.go
Instead, emit BadString with a special Error field
that can be examined by the linter later to emit a warning.
php-parser does only partial strings validation, so
we might encounter badly encoded UTF-8 escapes as
well as some other issues. We'll report them as a
syntax errors in linter.
Previously, interpretString() function assumed that
parsed string literals are valid PHP literals.
> ir/irconv: don't panic on invalid strings

- src/linter/report.go
Requiring phpdoc for public methods is good,
but for most projects it generates 90% of warnings
and it may be considered to be an unpleasant noise.
It's better to make NoVerify more user-friendly by
default, without any flags override (as it was a while ago).
> linter: disable phpdoc check by default

- src/cmd/main.go
- src/tests/golden/golden_test.go
Instead of doing a full stubs loading, use our dependencies
list from the golden tests to hint the linter which embedded
stubs need to be loaded.
With this, we significantly reduce the amount of work linter
needs to do before running the inspections.
On my machine, golden tests run for 40-50 seconds.
After this patch I get 5-8 seconds.
> tests: make e2e tests ~x6 faster

- src/cmd/php-guru/dupcode/main.go
- src/ir/helper_types.go
- src/ir/irconv/irconv.go
- src/ir/irfmt/printer_test.go
- src/ir/node_types.go
- src/ir/normalize/normalize_test.go
- src/langsrv/langsrv.go
- src/langsrv/refs.go
- src/linter/block.go
- src/linter/phpdoc_test.go
- src/linter/root.go
- src/linter/worker.go
- src/phpgrep/compile.go
- src/phpgrep/matcher_test.go
- src/rules/parser.go
The irconv package will now attempt to parse phpdoc for common
nodes like function/method/class statements if
Converter was created with phpdoc types parser.
(This API may change in the future!)
We need to do eager parsing in 99% of cases.
The only case where we don't want to do it
are phpgrep-like utils as well as some php-guru
parts that are not interested in phpdoc comments at all.
All packages that were parsing raw strings are changed to
use []phpdoc.CommentPart directly.
I returned irconv.ConvertNode() helper function to
make it easier to make AST->IR conversion in places
where we are too lazy to reuse the converter or
we don't care about their performance (some of these
places can be fixed later if we ever want to).
The main benefit of the eager phpdoc parsing is that
custom …
> ir: eagerly parse phpdoc in irconv

- src/solver/solver.go
- src/tests/checkers/oop_test.go
During type inference for a static::method call,
if the calling function internally makes another
static::method2 call, then a collision occurs
during type resolution.
To solve it, for "static" in r.visited,
"static" + class name is now stored as a key,
not just "static".
Fixes #776
> solver: fixed error with incorrect type inference for static::method calls

- src/ir/irutil/irtutil.go
- src/tests/checkers/discard_expr_test.go
> ir/irutil: fixed bug where assign null coalesce gave DiscardExpr warning

- src/linter/root.go
- src/tests/exprtype/exprtype_test.go
Due to the introduction of a new
`parseFuncArgsForCallback` function
for processing callback arguments,
we lost the type hints processing,
since an early exit from `parseFuncArgs`
is done and does not reach the type
hints processing. Therefore, we have
to process type hints explicitly.
> linter: fixed type inference for callback arguments if they have type hint

- src/linter/custom.go
- src/linter/root.go
- src/linter/worker.go
In order to be able to implement a third-party `RootChecker` with a state change before entering the file, we need these two methods.
> linter: added beforeEnterFile in RootWalker and BeforeEnterFile in RootChecker

- src/linter/regexpsimplify.go
- src/tests/checkers/regexpsimplify_test.go
Named capture always printed like ?P<name>, but it can have 2
more forms: ?<name> and ?'name'.
The quoted format is extra tricky as we always suggest '-quoted
replacements; we give up if we find this form to avoid invalid
suggestions. It's possible to suggest "-quoted literals in
the future, but it may require more changes (and tests).
> checkers: fix regexpsimplify handling of named capture alt forms

- src/solver/exprtype.go
The code for type inference has been moved to separate functions.
The order of functions has been changed, the main functions have been moved to the top.
Dots are put at the end of the comments.
> solver: small refactoring of exprtype.go

- src/constfold/binary_op.go
- src/constfold/eval.go
- src/constfold/unary_op.go
- src/ir/normalize/normalize.go
- src/linter/block_linter.go
- src/linter/root.go
- src/meta/const_value.go
- src/meta/metainfo.go
In the `eval` function, some direct constructs of the
`meta.ConstValue` structure has been replaced with
`meta.New[Type]Const` functions.
`meta.New[Type]Const` function names have been normalized.
A comment has been added for the `ConstValue.Get[Type]`,
`ConstValue.New[Type]Const`, `ConstValue.IsEqual` functions
and `ConstValue` structure.
The ConstInfo structure has been moved to a better
location – `metainfo.go`.
> constfold: refactoring related to constants

- src/workspace/files.go
In git mode, in the case of untracked files, the `gitParseUntracked` function is called, which passes the list of files to the `workspace.ReadFilenames` function, in which the `readFilenames` function is called for each file.
The problem is that if not a directory is passed, then the following code is executed
```go
if !st.IsDir() {
if filter.IgnoreFile(filename) {
return
}
ch <- FileInfo{Filename: filename}
return
}
```
Where there is no extension check, which is present when traversing a folder below the function.
Let's add a check here and the error will go away.
> workspace: fixed bug when untracked binary was added in git mode and this led to panic

- src/phpgrep/compile.go
- src/phpgrep/matcher.go
- src/phpgrep/matcher_test.go
- src/phpgrep/meta_nodes.go
- src/phpgrep/pattern_language.md
Matches FunctionCall, MethodCall, StaticCall.
Useful for the command-line github.com/quasilyte/phpgrep tool.
> phpgrep: add "call" meta node

- src/phpgrep/compile.go
- src/phpgrep/matcher.go
- src/phpgrep/matcher_test.go
- src/phpgrep/phpgrep.go
- src/phpgrep/tracing_test.go
Some symbols are case insensitive in PHP.
phpgrep always behaved in a case sensitive way, so
`f()` pattern would not match `F()` call.
Most of the time, it's not a desired effect, unless
we're looking for the exact spelling.
This change makes phpgrep more PHP-compatible by default
with ability to turn strict case sensitivity on via Compiler.
We can add a dynamic rule attribute that turns case sensitivity on later.
See https://github.com/quasilyte/phpgrep/issues/57
> phpgrep: follow PHP case sensitivity by default

- src/cmd/git_main.go
> cmd: add missing parseIndexOnlyFiles() calls

- src/cmd/flags.go
- src/cmd/linter_runner.go
- src/linter/conf.go
- src/linter/types.go
- src/tests/checkers/kphp_test.go
- src/tests/exprtype/kphp_test.go
This is needed so the KPHP code can work correctly.
To avoid confusion when NoVerify is used with PHP,
this behavior is implemented under the new -kphp flag.
> linter: interpret `any` type as `mixed`

- src/linter/custom.go
A getter has been added to get the content of the currently analyzed file, as well as a method for adding a quick fix for custom rules.
> linter: added the ability to add quick fixes in custom rules

- src/phpgrep/matcher.go
%*s is a "width", not a "repeat" operation...
> phpgrep: fix backtracking tracing pad

- src/linter/block_linter.go
- src/linter/report.go
- src/solver/oop.go
- src/tests/checkers/catch_test.go
When using multi-catch try statements, sometimes programmers get the
catch clause order wrong:
Catching derived exception after the base exception:
https://github.com/woocommerce/woocommerce/blob/1c65696535b4de34263554280c4ae7ef8b57d8ea/includes/legacy/api/class-wc-rest-legacy-orders-controller.php#L271
WC_REST_Exception extends WC_Data_Exception:
https://github.com/woocommerce/woocommerce/blob/1c65696535b4de34263554280c4ae7ef8b57d8ea/includes/class-wc-rest-exception.php#L16
dupCatch: report duplicated catch clauses.
try {
// some code
} catch (Exception1 $e) {
} catch (Exception1 $e) {} // <- note the typo
=>
try {
// some code
} catch (Exception1 $e) {
} catch (Exception2 $e) {}
catchOrder: Report erroneous catch order in try statements.
try {
// some code
} catch (Exception $e) {
// …
> linter: add dupCatch and catchOrder checkers

- .golangci.yml
- src/baseline/baseline.go
- src/cmd/main.go
- src/cmd/php-guru/dupcode/main.go
- src/cmd/php-guru/dupcode/utils.go
- src/git/blame.go
- src/git/catter.go
- src/git/diff.go
- src/git/ls.go
- src/git/mergebase.go
- src/ir/irfmt/printer.go
- src/langsrv/langsrv.go
- src/langsrv/state.go
- src/lintdoc/lintdoc_test.go
- src/linter/cache.go
- src/linter/cache_test.go
- src/linter/worker.go
- src/meta/typestring.go
Several cmd.Wait() errors were unchecked.
Places that were calling Output() eagerly are now simplified
to cmd.CombinedOutput(), so we don't need to do Output()+Wait() ourselves.
Most places ignored errors on purpose, but there were a couple of spots
where not ignoring an error would be nice to see that something goes wrong.
> all: enabled errcheck linter, fixed unchecked errors

- .golangci.yml
- src/cmd/rules.go
- src/constfold/eval.go
- src/ir/codegen/context.go
- src/ir/irconv/irconv_test.go
- src/langsrv/langsrv.go
- src/linter/block.go
- src/linter/report.go
- src/meta/const_value.go
- src/meta/typestring.go
- src/phpdoc/parser.go
- src/phpgrep/matcher_test.go
- src/solver/solver.go
- src/tests/checkers/misspell_test.go
- src/tests/golden/quickfix_test.go
- src/tests/rules/rules_error_test.go
Most range loop changes are due to the scopelint.
Capturing a loop variable into closure is not very reliable
and error-prone.
Instead of using this idiom:
for _, x := range xs {
x := x // Make it a normal local var
// use x
}
I used this one (I find it less confusion as it has no "self-assign"):
for i := range xs {
x := xs[i]
// use x
}
> all: enabled scopelint + more gocritic checkers

- src/linter/block.go
- src/linter/root.go
- src/linter/utils.go
- src/meta/typesmap.go
- src/solver/exprtype.go
- src/tests/exprtype/exprtype_test.go
The TypesMap.AppendString may mutate the map, which makes it harder
for us to migrate to fully immutable type maps.
The new Map() method is supposed to be used in places where we
want to create a new types map based on other types map.
All current AppendString usages were replaced and the method itself
is removed now.
> meta,linter: use TypesMap.Map instead of TypesMap.AppendString

- Makefile
- _script/release.go
It builds noverify for all supported platforms with version info.
It also creates zip archives to be uploaded.
> Makefile: add "build-release" target to make release building easier

- src/cmd/main.go
- src/cmd/subcmd.go
- src/linttest/golden_linttest.go
Now, when run without commands, help will be displayed.
> cmd: removed the deprecated way to run NoVerify

- src/linter/cache_test.go
- src/linter/parser.go
Let's not give 100 ways to run the linter.
> linter: remove deprecated parser funcs from linter API

- src/linter/and_walker.go
- src/linter/block.go
- src/linter/block_linter.go
- src/linter/custom.go
- src/linter/debug.go
- src/linter/limits.go
- src/linter/parser.go
- src/linter/root.go
- src/linter/utils.go
- src/linter/worker.go
Most notable, RootWalker and BlockWalker are unexported now.
> linter: unexport many symbols

- src/linter/block.go
- src/linter/cache.go
- src/linter/cache_test.go
- src/linter/custom.go
- src/linter/phpdoc_test.go
- src/linter/root.go
- src/linter/worker.go
- src/linttest/linttest.go
- src/tests/exprtype/exprtype_test.go
Now Parse functions return ParseResult struct instead of RootWalker.
> linter: unexported RootWalker

- src/linter/block_linter.go
- src/linter/root.go
The method was named `fmtNode`.
> linter: two methods for getting the string representation of a node are combined into one

- src/phpdoc/type_parser.go
- src/phpdoc/type_parser_test.go
Some type names, like `non-empty-list` contain '-' in their names.
We don't want to fail parsing those.
> phpdoc: fix type parser panic on type names with '-'

- src/ir/node_types.go
This is the first step in migrating to the new
a version of the php parser.
The new version of the parser moved away from
storing everything in free-floating and switched
to the concept of tokens.
> ir: added tokens to ir nodes

- src/meta/info.go
Since meta.Info is not global anymore, it's logical to
pass the actual Info object to the hook so it can operate
on the relevant object (the one that had the hook installed).
> meta: add *Info param to the post-indexing callbacks

- src/cmd/linter_runner.go
- src/linter/conf.go
- src/linter/root.go
During one of the previous refactorings the baseline hash
computations were broken for the baseline output mode.
This resulted in all report hashes to be 0.
This change makes linter compute hashes when --output-baseline is set
in addtion to the case when --baseline is a non empty string.
> linter: compute hashes when --output-baseline is set

- src/linter/block.go
- src/tests/checkers/oop_test.go
Since the presence of the parent construct during the
traversal of the function is in `blockWalker`, during
the processing of each static call `blockWalker.callsParentConstructor`
was overwritten, which led to a situation when there
is a call to the parent constructor, but another static
call (including in the arguments when calling the parent
constructor) overwritten the value to `false`.
> linter: fixed false positive of parentConstructor

- src/cmd/help.go
- src/cmd/linter_runner.go
- src/cmd/rules.go
- src/linter/block.go
- src/linter/conf.go
- src/linter/utils.go
- src/linttest/linttest.go
- src/rules/parser.go
- src/rules/rules.go
The `Config.Rules` field is now fully initialized, including
the fields of the `rules.Set` structure. Thus, we got rid of the
need to initialize this field every time.
The `InitEmbeddedRules` function has been renamed to `AddEmbeddedRules`
and now accepts not the config, but the rules directly, as well
as for the `appendRuleSet` function.
> cmd: small refactor rule init code

- src/cmd/flags.go
- src/linter/block.go
- src/linter/conf.go
- src/tests/checkers/trigger_error_test.go
Since some projects may use some recovery with set_error_handler,
there is a `-ignore-trigger-error` flag to disable this behavior.
> linter: treat trigger_error($msg, E_USER_ERROR) as exit()

- src/linter/worker.go
Due to the fact that the hash of the file was calculated
using the `contents` variable (which was always empty), and
not by the required `file.Contents()`, the hash of the file
was always the same.
This led to a situation in which a change in the file (for
example, adding a constant to a class) did not change its
cached data (information about the class without a new constant
remained in the cached data), since due to the fact that the
file with the cache for the current hash exists (that is,
the file `test.php_<hash_val>` exists), then there was no
repeated parsing of the file, which would update the data
(add information about the constant) and write it to the
cache.
In general, this was due to the fact that the function
signature changed from
```go
func IndexFile(filename string, …
```
> linter: fix cache error

- src/linter/block_linter.go
- src/linter/report.go
- src/tests/checkers/stripTags_test.go
Reports suspicious usage of `string_tags()` function.
More precisely, it checks that `$allowed_tags` argument is valid.
There are many ways to use this function incorrectly.
This checker tries to find the most common mistakes.
> linter: add stripTags checker

- src/linttest/golden_linttest.go
- src/tests/golden/golden_test.go
In view of the fact that we had cases when subcommands panicked after 
changes and this was not found, additional testing will not be superfluous.
> linttest: added the ability to test subcommands

- src/ir/get_first_token.go
- src/ir/irconv/irconv.go
- src/ir/irfmt/printer.go
- src/ir/irutil/clone.go
- src/ir/irutil/equal.go
- src/ir/node_types.go
- src/ir/normalize/normalize.go
- src/ir/walk.go
- src/linter/block.go
- src/linter/block_linter.go
- src/linter/root.go
- src/phpgrep/matcher.go
- src/solver/exprtype.go
- delete `Doc` from `PropertyStmt`
- rename all `Expression` to `Expr`
- removed a comment asking about the need for a separate node for magic constants
- `BadString` now consists of a `String` and an `Error` field
- fix typo in comment for `ContinueStmt`
- removed deprecated comment for `GroupUseStmt`
#866
> ir: refactor ir

- src/linter/block_linter.go
- src/linter/report.go
- src/tests/checkers/basic_test.go
See [deprecated core nested-ternary](https://www.php.net/manual/ru/migration74.deprecated.php#migration74.deprecated.core.nested-ternary).
> linter: added order check in nested ternary operator

- src/linter/types.go
- src/tests/exprtype/exprtype_test.go
The array type in tuple was resolved as `\array`, not `array`.
> linter: fixed a bug with a tuple containing an array

- src/linter/and_walker.go
- src/linter/block.go
- src/linter/block_linter.go
- src/linter/cache.go
- src/linter/cache_test.go
- src/linter/custom.go
- src/linter/root.go
- src/linter/root_context.go
- src/linter/types.go
- src/linter/utils.go
- src/linter/worker.go
- src/meta/const_value_test.go
- src/meta/info.go
- src/meta/metainfo.go
- src/meta/scope.go
- src/solver/closure.go
- src/solver/exprtype.go
- src/solver/solver.go
- src/solver/solver_test.go
- src/tests/bench/bench_test.go
- src/tests/checkers/basic_test.go
- src/tests/exprtype/exprtype_test.go
- src/types/typesmap.go
- src/types/typesmap_test.go
- src/types/typestring.go
- src/types/typestring_test.go
There are a lot of changes since all `meta.TypesMap` things were
renamed to `types.Map` (and there more examples like this).
One benefit is that if we decouple types and meta it
will be easier to further decompose indexdata types and
meta types (they both would need to use `types`, so we
more it to a separate package to avoid circular deps).
> linter,meta: move all types-related code to `types` package

- src/linter/block.go
- src/tests/checkers/disable_inspection_test.go
`@noinspection PhpUnreachableStatementInspection` 
annotation disable deadCode checking.
> linter: added support for @noinspection PhpUnreachableStatementInspection 

- src/linter/block.go
- src/tests/exprtype/exprtype_test.go
Now, any addition to a one-dimensional array is handled 
correctly, but in the case of multidimensional arrays, a simple 
replacement with mixed occurs and as a result, the type is 
deduced as `mixed[]`.
In this PR, I made the same behavior as for one-dimensional 
arrays, so now multidimensional arrays will be processed more 
correctly and do not require additional type annotations for 
variables.
> linter: improved type inference for multidimensional arrays

- src/meta/info.go
- src/tests/exprtype/kphp_test.go
Replace:
- `array_first_element` with `array_first_value`
- `array_last_element` with `array_last_value`
Initially, incorrect names of functions that are not in 
`kphp-polyfills` have been changed to correct ones.
#977
> meta: replace array_first_element with array_first_value

- src/linter/root.go
- src/tests/checkers/oop_test.go
Now the check does not work if there is a namespace. 
I think this can also be included in this PR, since this is 
also a kind of improvement 😄
> linter: improve oldStyleConstructor checker

- src/linter/cache_test.go
- src/meta/info.go
- src/meta/metainfo.go
- src/solver/exprtype.go
- src/tests/exprtype/kphp_test.go
- src/types/typesmap.go
Since type inference occurs before lazy types are resolved, 
this does not work entirely for function return types.
Perhaps we should add the ability to add a lazy type, which 
would say that when resolving types, need to remove a certain 
type, for example, `false` or `null`.
#977
> meta: add type inferring for not_null, not_false and create_vector from polyfills

- src/cmd/linter_runner.go
- src/cmd/main.go
And also renamed to `IsCriticalReport` and `IsEnabledReport`.
Since these functions take `linterRunner` as the first
argument, it makes sense to move them to methods and
at the same time move them to the file with `linterRunner`,
which will reduce the number of functions in `main.go`.
> cmd: isCritical and isEnabled moved to linterRunner methods

- src/cmd/embeddedrules/rules.php
- src/ir/normalize/normalize.go
- src/ir/phpcore/phpcore.go
- src/phpgrep/compile.go
- src/phpgrep/doc.go
- src/phpgrep/matcher.go
- src/phpgrep/matcher_test.go
- src/phpgrep/phpgrep.go
- src/phpgrep/utils.go
- src/rules/parser.go
- src/rules/rules.go
Dynamic rules will use this feature by default.
There is `@strict-syntax` attribute to disable this behavior explicitly.
> phpgrep: implement partially normalized (fuzzy) matching

- docs/dynamic-rules.md
- src/cmd/rules.go
`-rules` flag can now accept folders, in which case all files from it will be added to the rules
Please note that if there is another folder in the specified
folder and there are rules in it, these rules will **NOT** be added.
Only rules that are directly in the specified folder are added.
> cmd: -rules flag can now accept folders

- src/linter/block_linter.go
- src/linter/report.go
- src/tests/checkers/misspell_test.go
- src/tests/checkers/oop_test.go
- src/tests/golden/testdata/math/golden.txt
- src/tests/golden/testdata/mustache/golden.txt
- src/tests/golden/testdata/parsedown/golden.txt
- src/tests/golden/testdata/qrcode/golden.txt
- src/tests/golden/testdata/underscore/golden.txt
`classMembersOrder` checks that all constants and
properties of the class go before methods.
> linter: added classMembersOrder checker

- src/cmd/cli.go
- src/cmd/command.go
This flag defines the command, which itself is responsible for registering flags and arguments.
For the command with this flag, the help subcommand is not automatically generated.
> cmd: added Pure flag for cli.Command

- src/linter/types.go
- src/tests/checkers/phpdoc_test.go
Also fixed a bug where a nullable field in shape
caused the entire shape to become nullable.
> linter: added check for repeated nullable type

- src/linter/cache.go
- src/linter/cache_test.go
- src/linter/phpdoc_util.go
- src/meta/metainfo.go
These values are needed in order to distinguish between
methods and properties that are actually in the class and
which are defined in the annotation for the class.
> linter: added `*FromAnnotation` value for `meta.PropertyFlags` and `meta.FuncFlags`

- src/cmd/cli.go
Fixed panic that happens when no commandline arguments are given, arguments number check added before using them.
> added commandline arguments number check before using them

- Makefile
- _script/release.go
- main.go
- src/cmd/flags.go
- src/cmd/main.go
- src/cmd/version.go
- Added the `version` command to replace the `--version` flag
for the `check` command;
- Removed `--version` flag;
- Added a new field for version, now the `version` command
will also show the NoVerify version number;
- Build time will now be shown with delimiters.
- Variables for version, commit, etc. those set at compile-time 
have been moved to the `cmd` package, otherwise the `version`
command would be too difficult to do.
Before:
```
2021/07/03 12:55:42 built on: 20210703124446 OS: x86_64 Commit: 6a7e948f75816c274a98dfb5e35e00f97933bd14
```
After:
```
NoVerify, version 0.3.0: built on: 2021.07.03 12:44:46 OS: x86_64 Commit: 6a7e948f75816c274a98dfb5e35e00f97933bd14
```
> cmd: updated version handling

- src/linter/root.go
- src/tests/checkers/phpdoc_test.go
Fixed a bug where `@see CONSTANT_NAME` was given an 
error even if a constant was defined in the class.
PHPStorm correctly detects such a link.
Fixes #1016
> linter: fixed a bug for `@see CONSTANT_NAME`

- src/linter/root.go
- src/tests/checkers/basic_test.go
Fixed error when calling the define function with a slash at the beginning 
(`\define("One", 1)`) did not create a constant.
Fixed #1018
> linter: fixed error with define call

- docs/linter-usage.md
- src/cmd/embeddedrules/rules.php
- src/linter/block.go
- src/linter/root.go
- src/tests/checkers/basic_test.go
- src/tests/checkers/catch_test.go
- src/tests/checkers/oop_test.go
- src/tests/golden/testdata/embeddedrules/golden.txt
- src/tests/golden/testdata/flysystem/golden.txt
- src/tests/golden/testdata/idn/golden.txt
- src/tests/golden/testdata/math/golden.txt
- src/tests/golden/testdata/mustache/golden.txt
- src/tests/golden/testdata/parsedown/golden.txt
- src/tests/golden/testdata/phprocksyd/golden.txt
- src/tests/golden/testdata/qrcode/golden.txt
- src/tests/golden/testdata/twitter-api-php/golden.txt
- src/tests/golden/testdata/underscore/golden.txt
- src/tests/inline/testdata/embeddedrules/emptyStringCheck.php
- src/tests/inline/testdata/embeddedrules/returnAssign.php
- src/tests/inline/testdata/embeddedrules/strangeCast.php
- src/tests/regression/issue128_test.go
- src/tests/regression/issue252_test.go
- src/tests/regression/issue26_test.go
- src/tests/regression/issue288_test.go
- For embedded dynamic rules, all messages are capitalized;
- For messages with variables, added `$` before the variable name;
- For messages related to an unused variable added mention of the `--unused-var-regex` flag.
> linter: fixed different report messages

- src/linter/block_linter.go
- src/linter/custom.go
- src/linter/root.go
Now if the check is not enabled, quick fixes will not be applied for it.
Fixes #999
> linter: fixed quickfix

- src/linter/block.go
- src/linter/root.go
- src/phpdoc/type_parser.go
- src/phpdoctypes/converter.go
- src/phpdoctypes/parser.go
- src/tests/checkers/basic_test.go
- src/tests/exprtype/exprtype_test.go
- src/types/closure.go
For example:
```php
/**
* @param callable(): Foo $s
*/
function f1(callable $s) {
$a = $s();
exprtype($a, "\Foo");
}
```
Fixes #1006
> linter: added type inference for `callable` from PHPDoc

- src/phpdoctypes/converter.go
- src/tests/exprtype/exprtype_test.go
For `list<T>`, `non-empty-array<T>`, `non-empty-list<T>` and other unknown 
containers with '-' in the name, type `array<T>` is deduced.
Fixes #341
> phpdoctypes: add handling of unknown `types-with-dashes` annotations

- src/linter/block_linter.go
- src/linter/cache_test.go
- src/linter/report.go
- src/linter/root.go
- src/meta/metainfo.go
- src/state/update.go
- src/tests/checkers/oop_test.go
> linter: added check for `new` for traits and interfaces

- src/solver/exprtype.go
- src/tests/exprtype/exprtype_test.go
For example:
```php
/**
* @return Foo[]
*/
function f() {
return [];
}
function f1() {
$a = (array) f();
echo $a[0]->f();
}
```
```
<critical> ERROR   undefined: Call to undefined method {mixed}->f() at ...:16
echo $a[0]->f();
^
```
No error.
> solver: now typecast to an array does not overwrite existing types

- src/linter/block.go
- src/linter/utils.go
- src/meta/scope.go
- src/types/map.go
If the resulting type is `mixed[]`, then if the actual type is a specific
array type, then we use it, otherwise, we combine this type with the
resulting `mixed[`] type.
If a new element is added to an empty array, then the `empty_array` type
is removed.
#849
> linter: now, if the function returns array, then inferred type is taken into account

- src/linter/root.go
- src/tests/checkers/basic_test.go
- src/tests/golden/testdata/flysystem/golden.txt
> linter: added a check for using `void` type in the type union or `@param` annotation

- src/phpdoc/type_parser_test.go
- src/phpdoctypes/converter.go
- src/tests/exprtype/exprtype_test.go
For example:
```php
/**
* @param array{int, name: string} is shape<0: int, name: string>
* @param array{name: string, int} is shape<1: int, name: string>
*/
```
> This syntax is correct for Psalm.
> phpdoctypes: added support for mixing in `array{}`

- src/cmd/embeddedrules/rules.php
- src/linter/block_linter.go
- src/linter/report.go
- src/tests/checkers/basic_test.go
- src/tests/checkers/codedup_test.go
- src/tests/golden/testdata/flysystem/golden.txt
- src/tests/golden/testdata/idn/golden.txt
- src/tests/golden/testdata/inflector/golden.txt
- src/tests/golden/testdata/mustache/golden.txt
- src/tests/golden/testdata/options-resolver/golden.txt
- src/tests/golden/testdata/qrcode/golden.txt
- src/tests/golden/testdata/quickfix/unaryRepeat.php
- src/tests/golden/testdata/quickfix/unaryRepeat.php.fix.expected
- src/tests/inline/testdata/checkers/dupBranchBody.php
- src/tests/inline/testdata/checkers/switchDefault.php
- src/tests/inline/testdata/checkers/switchEmpty.php
- src/tests/inline/testdata/checkers/switchSimplify.php
- src/tests/inline/testdata/embeddedrules/alwaysNull.php
- src/tests/inline/testdata/embeddedrules/countUse.php
- src/tests/inline/testdata/embeddedrules/errorSilence.php
- src/tests/inline/testdata/embeddedrules/forLoop.php
- src/tests/inline/testdata/embeddedrules/selfAssign.php
- src/tests/inline/testdata/embeddedrules/unaryRepeat.php
- src/tests/regression/issue170_test.go
- src/tests/regression/issue252_test.go
- src/tests/regression/issue78_test.go
- countUse (https://rules.sonarsource.com/php/type/Bug/RSPEC-3981)
- improved `dupBranchBody` checker, added handling switch cases, and improved message for `dupCond` checkers for switch cases (https://rules.sonarsource.com/php/type/Bug/RSPEC-3923)
- unaryRepeat (https://rules.sonarsource.com/php/type/Bug/RSPEC-2761)
- forLoop (https://rules.sonarsource.com/php/type/Bug/RSPEC-2251)
- alwaysNull (https://rules.sonarsource.com/php/type/Bug/RSPEC-1697)
- selfAssign (https://rules.sonarsource.com/php/type/Bug/RSPEC-1656)
- errorSilence (https://rules.sonarsource.com/php/type/Bug/RSPEC-2002)
- switchDefault (https://rules.sonarsource.com/php/type/Code%20Smell/RSPEC-131 https://rules.sonarsource.com/php/type/Code%20Smell/RSPEC-4524)
- switchSimplify …
> linter: added checks from SonarLint

- src/ir/location.go
- src/linter/custom.go
- src/linter/phpdoc_util.go
- src/linter/root.go
- src/tests/golden/testdata/baseline-test/baseline.json
- src/tests/golden/testdata/output-test/golden.txt
- src/tests/golden/testdata/output-test/output_test.php
Now at the heart of all the functions for creating reports
is a function that creates a report at a given location.
`Report` and `ReportPHPDoc` are now wrappers that convert `node`
and `PHPDocLocation` to `Location` for `ReportLocation`.
`ReportByLine` has been removed as it is no longer used and
can be replaced with `ReportLocation`.
Fixed error, if the warning was given on the last line in
the file, then the context line was empty.
A new `ir.Location` structure has been added.
`ir.Location` stores the shifts relative to the current line.
A new structure is needed since `position.Position` stores
line shifts relative to the beginning of the file, not
relative to the current line, which is inconvenient for
using `ReportLocation`.
> linter: refactored report functions

- src/linter/block.go
- src/tests/exprtype/exprtype_test.go
Now, if there is a variable on the left of the assignment, then
the type from `@var` is set for it, even if the variable name is
not specified.
Before:
```php
function f($a) {
/**
* @var Foo
*/
$b = $a;
exprtype($b, "mixed");
}
```
After:
```php
function f($a) {
/**
* @var Foo
*/
$b = $a;
exprtype($b, "\Foo|mixed");
}
```
Used and supported by Psalm.
Reduces the number of `undefined` reports by 64 when parsing Psalm.
> linter: added support when no variable is specified for `@var`

- src/ir/irconv/irconv.go
- src/tests/checkers/oop_test.go
Previously, if a class had modifiers, then PHPDoc was not attached to the class.
> irconv: fixed PHPDoc for class with modifiers

- src/linter/report.go
- src/linter/root.go
- src/tests/checkers/basic_test.go
- src/tests/checkers/oop_test.go
- src/tests/checkers/typehint_test.go
- src/tests/golden/testdata/math/golden.txt
- src/tests/golden/testdata/parsedown/golden.txt
- src/tests/regression/issue778_test.go
It checks that an explicit access level is specified for the methods and properties of the class
> linter: added `implicitModifiers` checker

- src/ir/irutil/irtutil.go
- src/linter/report.go
- src/linter/root.go
- src/meta/metainfo.go
- src/tests/inline/testdata/checkers/methodSignatureMismatch.php
It checks that the method does not override the final method from the base class.
> linter: added `methodSignatureMismatch` checker

- src/linter/block_linter.go
- src/linter/report.go
- src/tests/checkers/functions_test.go
It checks if parameters are passed in reverse order.
For functions with two parameters only.
> linter: added `argsReverse` checker

- src/cmd/check.go
- src/cmd/main.go
- src/cmd/rules.go
This is necessary to load the rules into the playground.
> cmd: exported `ParseExternalRules` and `ParseExternalRules` functions

- src/cmd/main.go
This is necessary to load the stubs into the playground.
> cmd: exported `InitStubs` functions

- src/meta/info.go
Since we have to re-analyze each file change in the Playground, we need a 
way not to load stubs and rules every time, since it takes about 1 second.
We can load them once and then each analysis clone the `Info` struct and 
create a new linter based on it.
We cannot use `Info` with stubs directly without cloning, as this will lead to 
the fact that removing the function, for example, will not lead to errors, since 
the function will not actually be removed from `Info`.
> meta: added `Clone` method to `Info` struct

- src/linter/linter.go
See #1067
After we clone `Info`, we need to create a linter with this 
particular instance of `Info` structure, so we need this constructor.
> linter: added `NewLinterWithInfo` function

- src/cmd/git_main.go
- src/cmd/linter_runner.go
- src/cmd/main.go
We need to use `LinterRunner` to properly initialize the linter for Playground.
> cmd: export `LinterRunner` struct

- src/solver/exprtype.go
- src/tests/regression/issue1071_test.go
> solver: fixed type inference for the functions starts with a backslash

- src/cmd/embeddedrules/rules.php
- src/linter/block_linter.go
- src/linter/report.go
- src/tests/inline/testdata/embeddedrules/strangeCast.php
Now no warning will be issued for unary plus with
constant expression.
For example:
```php
$a = +100;
$a = +CONST_A;
```
> cmd: improved `strangeCast` checker

- docs/checkers_doc.md
- src/linter/block_linter.go
- src/linter/report.go
- src/tests/inline/testdata/checkers/reverseAssign.php
For example:
```php
$a =- 100;
// or
$a =+ 100;
```
> linter: added `reverseAssign` checker

- src/linter/regexpvet.go
- src/tests/inline/testdata/checkers/regexpVet.php
Do not analyze modifiers when there is an invalid modifier
char in the top-level modifiers group.
> linter: fix regexp modifiers analysis

- docs/checkers_doc.md
- src/linter/block.go
- src/linter/block_linter.go
- src/linter/report.go
- src/linter/root.go
- src/tests/checkers/basic_test.go
- src/tests/checkers/oop_test.go
- src/tests/golden/testdata/baseline-test/baseline.json
- src/tests/golden/testdata/baseline-test/golden.txt
- src/tests/golden/testdata/mustache/golden.txt
- src/tests/golden/testdata/parsedown/golden.txt
- src/tests/golden/testdata/phprocksyd/golden.txt
- src/tests/golden/testdata/qrcode/golden.txt
- src/tests/golden/testdata/underscore/golden.txt
- src/tests/regression/issue16_test.go
- src/tests/regression/issue288_test.go
- `maybeUndefined`
- `undefinedConstant`
- `undefinedFunction`
- `undefinedMethod`
- `undefinedProperty`
- `undefinedType`
- `undefinedVariable`
> linter: split `undefined` checker into the following

- src/linter/worker.go
- src/utils/utils.go
Now the error "Failed parsing ..." is not shown if the error occurred in the `vendor` folder.
> linter: fixed the error "Failed parsing ..." for `vendor` folder

- src/cmd/stat/Makefile
- src/cmd/stat/README.md
- src/cmd/stat/go.mod
- src/cmd/stat/main.go
A tool for comparing reports between versions. At the output, it creates a markdown file with the results.
Run:
```shell
cd src/cmd/stat
make compare -i PROJECT_DIR=/Users/petrmakhnev/psalm/ NOVERIFY_ARGS='--index-only-files="./stubs" ./src'
```
The current master is automatically cloned into the folder, compiles and runs the analysis of the project on it If the master is already cloned, it will be updated.
> cmd/stat: added a tool for comparing reports between versions

- src/linter/block.go
- src/tests/golden/testdata/underscore/golden.txt
> linter: changed severity level for the `unused` checker to Warning

- src/linter/block.go
- src/linter/block_linter.go
- src/linter/root.go
- src/tests/checkers/basic_test.go
- src/tests/checkers/deadcode_test.go
- src/utils/utils.go
In the following cases:
```php
$undefinedVar ?? 100
isset($undefinedVar)
```
no need to throw a warning about an undefined variable,
since these constructs are used to check that the
variable is defined.
Fixes #1007
> linter: improved `undefinedVariable` and `maybeUndefined` checkers

- src/linter/block.go
- src/linter/root.go
- src/tests/checkers/basic_test.go
- src/tests/checkers/catch_test.go
- src/tests/checkers/oop_test.go
- src/tests/checkers/strict_mixed_test.go
- src/tests/golden/testdata/parsedown/golden.txt
- src/tests/golden/testdata/qrcode/golden.txt
- src/tests/regression/issue128_test.go
- src/tests/regression/issue252_test.go
- src/tests/regression/issue26_test.go
- src/tests/regression/issue288_test.go
```
undefinedVariable: Undefined variable $name
maybeUndefined: Variable $name might have not been defined
```
```
undefinedVariable: Cannot find referenced variable $name
maybeUndefined: Possibly undefined variable $name
```
> linter: improved `undefinedVariable` and `maybeUndefined` checkers messages

- src/linter/block.go
- src/linter/block_linter.go
- src/linter/phpdoc_test.go
- src/linter/quickfix.go
- src/linter/root.go
- src/linter/root_checker.go
- src/linter/worker.go
- src/types/typehint.go
> linter: move checks from `rootIndexer` to `rootChecker`

- docs/checkers_doc.md
- src/linter/block_linter.go
- src/linter/report.go
- src/tests/inline/testdata/checkers/parentNotFound.php
```php
class Foo {
public function f() {
parent::b(); // Class Foo has no parent.
}
}
```
> linter: added `parentNotFound` checker

- docs/checkers_doc.md
- src/linter/block.go
- src/linter/report.go
- src/linter/root.go
- src/linter/root_checker.go
- src/tests/checkers/phpdoc_test.go
- src/tests/golden/testdata/flysystem/golden.txt
- src/tests/golden/testdata/inflector/golden.txt
- src/tests/golden/testdata/options-resolver/golden.txt
- src/tests/golden/testdata/phpdoc/golden.txt
- src/tests/golden/testdata/phprocksyd/golden.txt
- src/tests/golden/testdata/twitter-api-php/golden.txt
`phpdocLint` => `invalidDocblock`
`phpdocType` => `invalidDocblockType`
`phpdocRef` => `invalidDocblockRef`
> linter: renamed `phpdoc*` checkers as in Psalm

- docs/checkers_doc.md
- src/linter/block_linter.go
- src/linter/report.go
- src/tests/checkers/deprecated_test.go
- src/tests/golden/testdata/flysystem/golden.txt
`deprecated` checker is divided into two `deprecated`
and `deprecatedUntagged`, where the first will be
triggered if there is a description for @deprecated,
and the second if there is none.
> linter: improved and enabled `deprecated` checkers

- src/ir/irconv/irconv.go
- src/ir/node_types.go
- src/phpgrep/matcher.go
- src/tests/checkers/catch_test.go
- src/tests/exprtype/exprtype_test.go
- src/types/map.go
> linter, ir: fixed panic on `catch` without variable and `types.Map.Erase` method

- src/attributes/attributes.go
- src/attributes/utils.go
- src/ir/irconv/irconv.go
- src/ir/methods.go
- src/linter/block.go
- src/linter/block_linter.go
- src/linter/cache.go
- src/linter/cache_test.go
- src/linter/root.go
- src/linttest/inline.go
- src/meta/metainfo.go
- src/phpdoctypes/parser.go
- src/rules/rules.go
- src/solver/closure.go
- src/tests/checkers/deprecated_test.go
- src/tests/checkers/phpdoc_test.go
- src/tests/exprtype/php8_test.go
- src/tests/golden/testdata/options-resolver/golden.txt
- src/tests/golden/testdata/phprocksyd/golden.txt
- src/tests/golden/testdata/underscore/golden.txt
- src/tests/inline/testdata/php8/deprecated_annotation_any.php
- src/tests/inline/testdata/php8/param_available_any.php
- src/utils/utils.go
- Added support for `Deprecated` annotation for functions
- Added support for `LanguageLevelTypeAware` annotation for functions return and param types
- Added support for `PhpStormStubsElementAvailable` for functions params
- Use info from `@removed` tag
- If `@deprecated` is empty for a function, but `@see` is present, then its value will be used as if `@deprecated` says `"use $see_text instead"`. Several `@see` will be concatenated and outputted with ` or ` separator
Fixed #576
Fixed #542
> linter: added support for some attributes and moved to `phpstorm-stubs` upstream

- src/cmd/embeddedrules/rules.php
- src/linter/report.go
- src/linter/root.go
- src/linttest/inline.go
- src/tests/inline/testdata/php8/propertyPromotion_any.php
Chevere: https://github.com/chevere/chevere
- Added support for property promotion
- `returnAssign`, `voidResultUsed`, and `parentNotFound` disabled by default and will fix and improve
This seems to be correct since the result is not used.
```
<critical> WARNING discardExpr: Expression evaluated but not used at /Users/petrmakhnev/chevere/src/Chevere/Components/Action/Action.php:76
new Arguments($this->responseParameters, ...$namedData);
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Correct, `name` is static
```
<critical> WARNING callStatic: Calling static method as instance method at /Users/petrmakhnev/chevere/src/Chevere/Components/Router/Route/RouteEndpoints.php:30
$routeEndpoint->method()->name(),
^^^^
```
~~Incorrect, an analysis is required for reflection~~. **Fixed.** …
> linter: fixed false positives in Chevere projects

- src/ir/irconv/irconv.go
This affected checks that depended on tokens.
> added lost `EmptyTkn` in irconv for `ExprEmpty`

- docs/dynamic_rules.md
- src/linter/root.go
- src/rules/parser.go
- src/rules/rules.go
- src/tests/rules/rules_test.go
> added @filter for dynamic rules

- src/ir/phpcore/phpcore.go
- src/phpgrep/matcher.go
- src/phpgrep/phpgrep.go
When matching things like `sizeof(...)` phpgrep would interpret it as `count(...)`, since sizeof is just an alias.
It breaks when we actually need to get the `sizeof` identifier position as `phpcore.ResolveAlias` returns a node without pos info.
This causes a runtime panic in phpgrep when such node is being rendered.
The current fix is to create a new node that has the resolved name value and original source location info.
> phpgrep: fix functions alias matching

- src/linter/utils.go
- src/rules/parser.go
- src/rules/rules.go
- src/rules/util.go
- src/tests/rules/rules_error_test.go
- src/tests/rules/rules_test.go
More about feature [here](https://github.com/VKCOM/noverify/issues/1208).
> dinamic rules: multiple path

- docs/dynamic_rules.md
- src/rules/parser.go
- src/rules/rules.go
- src/rules/util.go
- src/tests/rules/rules_test.go
It would be convenient to group a list of paths so that the rules are more compact.
```
/**
* @path-group-name GROUP1 <- something like id for group
* @path VK/Connect <- path in GROUP1
* @path ... <- another path in GROUP1
*/
/**
* @path-group GROUP1
* @warning please, use AppFacade::getApp() in GROUP1 code
*/
getApp();
/**
* @path /
* @path-group-exclude GROUP1
* @warning please, use getApp() outside GROUP1 code
*/
AppFacade::getApp();
/**
* @path-group GROUP1
* @path-exlude TestApp/Connect/Apps
* @warning please, use AppFacade::getApp() in GROUP1 code
*/
rpcCall(CLUSTER_APPLICATIONS); 
```
> dynamic rules: paths grouping

- docs/checkers_doc.md
- src/linter/block.go
- src/linter/block_linter.go
- src/linter/report.go
- src/tests/checkers/null_safety_test.go
- src/tests/golden/golden_test.go
- src/tests/golden/testdata/embeddedrules/golden.txt
- src/tests/golden/testdata/flysystem/golden.txt
- src/tests/golden/testdata/idn/golden.txt
- src/tests/golden/testdata/inflector/golden.txt
- src/tests/golden/testdata/math/golden.txt
- src/tests/golden/testdata/mustache/golden.txt
- src/tests/golden/testdata/options-resolver/golden.txt
- src/tests/golden/testdata/parsedown/golden.txt
- src/tests/golden/testdata/phprocksyd/golden.txt
- src/tests/golden/testdata/qrcode/golden.txt
- src/tests/golden/testdata/twitter-api-php/golden.txt
- src/tests/golden/testdata/underscore/golden.txt
- src/types/predicates.go
[Here](https://github.com/VKCOM/noverify/pull/1245) we added checking null-safety. Here we expanded it for statics and functions
> linter: null-safety for static calls, static/non static/ property fetching

- src/linter/block.go
- src/linter/block_linter.go
- src/linter/report.go
- src/tests/checkers/func_params_type_mismatch_phpdoc_test.go
- src/tests/checkers/not_explicit_nullable_types_test.go
- src/tests/golden/testdata/mustache/golden.txt
- src/types/map.go
- src/types/predicates.go
We have rule for nullability and i wanna extend checking the compliance of what is in typehints and phpdoc:
> linter: function param type mismatch with phpdoc
